/*
 * generated by Xtext
 */
package de.cau.cs.kieler.kiml.klayoutdata.text.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class KLayoutDataUiModule extends de.cau.cs.kieler.kiml.klayoutdata.text.ui.AbstractKLayoutDataUiModule {
	public KLayoutDataUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
