/*
 * generated by Xtext
 */
package de.cau.cs.kieler.core.krendering.text.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class KRenderingUiModule extends de.cau.cs.kieler.core.krendering.text.ui.AbstractKRenderingUiModule {
	public KRenderingUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
