/*
* generated by Xtext
*/
package de.cau.cs.kieler.kiml.klayoutdata.text.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.cau.cs.kieler.kiml.klayoutdata.text.services.KLayoutDataGrammarAccess;

public class KLayoutDataParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private KLayoutDataGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.cau.cs.kieler.kiml.klayoutdata.text.parser.antlr.internal.InternalKLayoutDataParser createParser(XtextTokenStream stream) {
		return new de.cau.cs.kieler.kiml.klayoutdata.text.parser.antlr.internal.InternalKLayoutDataParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "KShapeLayout";
	}
	
	public KLayoutDataGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(KLayoutDataGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
