/*
* generated by Xtext
*/
package de.cau.cs.kieler.core.kgraph.text.ui.contentassist;

import de.cau.cs.kieler.core.kgraph.text.ui.contentassist.AbstractKGraphProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class KGraphProposalProvider extends AbstractKGraphProposalProvider {

}
