<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="krendering"
    nsURI="http://kieler.cs.cau.de/KRendering" nsPrefix="krendering">
  <eClassifiers xsi:type="ecore:EClass" name="KPosition" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="KRelativePosition" eSuperTypes="#//KPosition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xRelative" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yRelative" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="offset" eType="#//KAbsolutePosition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KAbsolutePosition" eSuperTypes="#//KPosition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KRendering" abstract="true" eSuperTypes="../../de.cau.cs.kieler.core.kgraph/model/kgraph.ecore#//KGraphData">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//KBounded"
        eOpposite="#//KBounded/children"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="styles" upperBound="-1"
        eType="#//KStyle" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KEllipse" eSuperTypes="#//KBounded"/>
  <eClassifiers xsi:type="ecore:EClass" name="KRectangle" eSuperTypes="#//KBounded"/>
  <eClassifiers xsi:type="ecore:EClass" name="KRoundedRectangle" eSuperTypes="#//KBounded">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cornerWidth" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cornerHeight" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KPolyline" eSuperTypes="#//KRendering">
    <eStructuralFeatures xsi:type="ecore:EReference" name="points" lowerBound="1"
        upperBound="-1" eType="#//KPosition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decorators" upperBound="-1"
        eType="#//KDecorator" containment="true" eOpposite="#//KDecorator/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KPolygon" eSuperTypes="#//KPolyline"/>
  <eClassifiers xsi:type="ecore:EClass" name="KImage" eSuperTypes="#//KBounded"/>
  <eClassifiers xsi:type="ecore:EClass" name="KDecorator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//KPolyline" eOpposite="#//KPolyline/decorators"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rendering" eType="#//KRendering"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KBounded" abstract="true" eSuperTypes="#//KRendering">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//KRendering" containment="true" eOpposite="#//KRendering/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topLeft" lowerBound="1"
        eType="#//KPosition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bottomRight" lowerBound="1"
        eType="#//KPosition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KCustomRendering" eSuperTypes="#//KRendering">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="customRendering" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KArc" eSuperTypes="#//KBounded">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startAngle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arcAngle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KStyle"/>
  <eClassifiers xsi:type="ecore:EClass" name="KCompoundStyle" eSuperTypes="#//KStyle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="styles" upperBound="-1"
        eType="#//KStyle" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KRenderingLibrary" eSuperTypes="../../de.cau.cs.kieler.core.kgraph/model/kgraph.ecore#//KGraphData">
    <eStructuralFeatures xsi:type="ecore:EReference" name="renderings" upperBound="-1"
        eType="#//KRendering" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KRenderingRef" eSuperTypes="#//KRendering">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rendering" lowerBound="1"
        eType="#//KRendering"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KChildArea" eSuperTypes="#//KRendering"/>
  <eClassifiers xsi:type="ecore:EClass" name="KText" eSuperTypes="#//KBounded">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KCustomRendering" eSuperTypes="#//KRendering">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="customRendering" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
</ecore:EPackage>
