/*
 * generated by Xtext 2.12.0
 */
package de.cau.cs.kieler.kgraph.text.ide;


/**
 * Use this class to register ide components.
 */
public class GRandomIdeModule extends AbstractGRandomIdeModule {
}
