/*
 * generated by Xtext
 */
package de.cau.cs.kieler.core.krendering.text;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class KRenderingRuntimeModule extends de.cau.cs.kieler.core.krendering.text.AbstractKRenderingRuntimeModule {

}
