/*
* generated by Xtext
*/
package de.cau.cs.kieler.core.kgraph.text.klayoutdata.ui.contentassist;

import de.cau.cs.kieler.core.kgraph.text.klayoutdata.ui.contentassist.AbstractKLayoutDataProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class KLayoutDataProposalProvider extends AbstractKLayoutDataProposalProvider {

}
