/*
 * generated by Xtext 2.9.2
 */
package de.cau.cs.kieler.kgraph.text;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GRandomRuntimeModule extends AbstractGRandomRuntimeModule {
}
