/*
 * KIELER - Kiel Integrated Environment for Layout Eclipse RichClient
 *
 * http://www.informatik.uni-kiel.de/rtsys/kieler/
 *
 * Copyright 2021 by
 * + Kiel University
 *   + Department of Computer Science
 *     + Real-Time and Embedded Systems Group
 *
 * generated by Xtext 2.9.2
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package de.cau.cs.kieler.kgraph.text;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class GRandomStandaloneSetup extends GRandomStandaloneSetupGenerated {

	public static void doSetup() {
		new GRandomStandaloneSetup().createInjectorAndDoEMFRegistration();
	}				
}
