/*
 * KIELER - Kiel Integrated Environment for Layout Eclipse RichClient
 *
 * http://www.informatik.uni-kiel.de/rtsys/kieler/
 *
 * Copyright 2021 by
 * + Kiel University
 *   + Department of Computer Science
 *     + Real-Time and Embedded Systems Group
 *
 * generated by Xtext 2.9.2
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package de.cau.cs.kieler.kgraph.text;

import org.eclipse.xtext.formatting.IFormatter;

import de.cau.cs.kieler.kgraph.text.formatting.GRandomFormatter;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GRandomRuntimeModule extends AbstractGRandomRuntimeModule {
    
    /**
     * {@inheritDoc}
     */
    @Override
    public Class<? extends IFormatter> bindIFormatter() {
        return GRandomFormatter.class;
    }
}
