/*
 * generated by Xtext
 */
package de.cau.cs.kieler.core.kgraph.text.krendering;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class KRenderingRuntimeModule extends AbstractKRenderingRuntimeModule {

}
