/*
 * generated by Xtext 2.10.0
 */
package de.cau.cs.kieler.kgraph.text.parser.antlr;

import com.google.inject.Inject;
import de.cau.cs.kieler.kgraph.text.parser.antlr.internal.InternalGRandomParser;
import de.cau.cs.kieler.kgraph.text.services.GRandomGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class GRandomParser extends AbstractAntlrParser {

	@Inject
	private GRandomGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGRandomParser createParser(XtextTokenStream stream) {
		return new InternalGRandomParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "RandGraph";
	}

	public GRandomGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GRandomGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
