/*
 * generated by Xtext 2.9.2
 */
package de.cau.cs.kieler.kgraph.text.parser.antlr;

import com.google.inject.Inject;
import de.cau.cs.kieler.kgraph.text.parser.antlr.internal.InternalKGraphParser;
import de.cau.cs.kieler.kgraph.text.services.KGraphGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class KGraphParser extends AbstractAntlrParser {

	@Inject
	private KGraphGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalKGraphParser createParser(XtextTokenStream stream) {
		return new InternalKGraphParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ParentKNode";
	}

	public KGraphGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(KGraphGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
