/*
 * generated by Xtext
 */
package de.cau.cs.kieler.core.krendering.text.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.cau.cs.kieler.core.krendering.text.ui.internal.KRenderingActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class KRenderingExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return KRenderingActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return KRenderingActivator.getInstance().getInjector(KRenderingActivator.DE_CAU_CS_KIELER_CORE_KRENDERING_TEXT_KRENDERING);
	}
	
}
