/*
 * generated by Xtext
 */
package de.cau.cs.kieler.kiml.klayoutdata.text;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class KLayoutDataRuntimeModule extends de.cau.cs.kieler.kiml.klayoutdata.text.AbstractKLayoutDataRuntimeModule {

}
