/*
 * KIELER - Kiel Integrated Environment for Layout Eclipse RichClient
 * 
 * http://www.informatik.uni-kiel.de/rtsys/kieler/
 * 
 * Copyright 2012 by
 * + Christian-Albrechts-University of Kiel
 *   + Department of Computer Science
 *     + Real-Time and Embedded Systems Group
 * 
 * This code is provided under the terms of the Eclipse Public License (EPL).
 * See the file epl-v10.html for the license text.
 */
package de.cau.cs.kieler.core.kgraph.text;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages without equinox extension registry.
 * 
 * @author generated by Xtext, modified by chsch
 * @kieler.ignore (excluded from review process)
 */
public class KGraphStandaloneSetup extends KGraphStandaloneSetupGenerated {

    /**
     * Common initializer.
     * 
     * @author chsch (slightly modified)
     * 
     * @return a KGraph-specific injector
     */
    public static Injector doSetup() {
        return new KGraphStandaloneSetup().createInjectorAndDoEMFRegistration();
    }
}
