/*
* generated by Xtext
*/

package de.cau.cs.kieler.core.kgraph.text.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import de.cau.cs.kieler.core.krendering.text.services.KRenderingGrammarAccess;
import de.cau.cs.kieler.kiml.klayoutdata.text.services.KLayoutDataGrammarAccess;

@Singleton
public class KGraphGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class KNodeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "KNode");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cKNodeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cKNodeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cIncomingEdgesKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cIncomingEdgesAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final CrossReference cIncomingEdgesKEdgeCrossReference_3_2_0 = (CrossReference)cIncomingEdgesAssignment_3_2.eContents().get(0);
		private final RuleCall cIncomingEdgesKEdgeEStringParserRuleCall_3_2_0_1 = (RuleCall)cIncomingEdgesKEdgeCrossReference_3_2_0.eContents().get(1);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cIncomingEdgesAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final CrossReference cIncomingEdgesKEdgeCrossReference_3_3_1_0 = (CrossReference)cIncomingEdgesAssignment_3_3_1.eContents().get(0);
		private final RuleCall cIncomingEdgesKEdgeEStringParserRuleCall_3_3_1_0_1 = (RuleCall)cIncomingEdgesKEdgeCrossReference_3_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDataKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cDataAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cDataKGraphDataParserRuleCall_4_2_0 = (RuleCall)cDataAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cDataAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cDataKGraphDataParserRuleCall_4_3_1_0 = (RuleCall)cDataAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLabelsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cLabelsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cLabelsKLabelParserRuleCall_5_2_0 = (RuleCall)cLabelsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cLabelsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cLabelsKLabelParserRuleCall_5_3_1_0 = (RuleCall)cLabelsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cChildrenKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cChildrenAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cChildrenKNodeParserRuleCall_6_2_0 = (RuleCall)cChildrenAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cChildrenAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cChildrenKNodeParserRuleCall_6_3_1_0 = (RuleCall)cChildrenAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cPortsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cPortsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cPortsKPortParserRuleCall_7_2_0 = (RuleCall)cPortsAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cPortsAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cPortsKPortParserRuleCall_7_3_1_0 = (RuleCall)cPortsAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cOutgoingEdgesKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cOutgoingEdgesAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cOutgoingEdgesKEdgeParserRuleCall_8_2_0 = (RuleCall)cOutgoingEdgesAssignment_8_2.eContents().get(0);
		private final Group cGroup_8_3 = (Group)cGroup_8.eContents().get(3);
		private final Keyword cCommaKeyword_8_3_0 = (Keyword)cGroup_8_3.eContents().get(0);
		private final Assignment cOutgoingEdgesAssignment_8_3_1 = (Assignment)cGroup_8_3.eContents().get(1);
		private final RuleCall cOutgoingEdgesKEdgeParserRuleCall_8_3_1_0 = (RuleCall)cOutgoingEdgesAssignment_8_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8_4 = (Keyword)cGroup_8.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//KNode:
		//	{KNode} "KNode" "{" ("incomingEdges" "(" incomingEdges+=[KEdge|EString] ("," incomingEdges+=[KEdge|EString])* ")")?
		//	("data" "{" data+=KGraphData ("," data+=KGraphData)* "}")? ("labels" "{" labels+=KLabel ("," labels+=KLabel)* "}")?
		//	("children" "{" children+=KNode ("," children+=KNode)* "}")? ("ports" "{" ports+=KPort ("," ports+=KPort)* "}")?
		//	("outgoingEdges" "{" outgoingEdges+=KEdge ("," outgoingEdges+=KEdge)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//{KNode} "KNode" "{" ("incomingEdges" "(" incomingEdges+=[KEdge|EString] ("," incomingEdges+=[KEdge|EString])* ")")?
		//("data" "{" data+=KGraphData ("," data+=KGraphData)* "}")? ("labels" "{" labels+=KLabel ("," labels+=KLabel)* "}")?
		//("children" "{" children+=KNode ("," children+=KNode)* "}")? ("ports" "{" ports+=KPort ("," ports+=KPort)* "}")?
		//("outgoingEdges" "{" outgoingEdges+=KEdge ("," outgoingEdges+=KEdge)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{KNode}
		public Action getKNodeAction_0() { return cKNodeAction_0; }

		//"KNode"
		public Keyword getKNodeKeyword_1() { return cKNodeKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("incomingEdges" "(" incomingEdges+=[KEdge|EString] ("," incomingEdges+=[KEdge|EString])* ")")?
		public Group getGroup_3() { return cGroup_3; }

		//"incomingEdges"
		public Keyword getIncomingEdgesKeyword_3_0() { return cIncomingEdgesKeyword_3_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_3_1() { return cLeftParenthesisKeyword_3_1; }

		//incomingEdges+=[KEdge|EString]
		public Assignment getIncomingEdgesAssignment_3_2() { return cIncomingEdgesAssignment_3_2; }

		//[KEdge|EString]
		public CrossReference getIncomingEdgesKEdgeCrossReference_3_2_0() { return cIncomingEdgesKEdgeCrossReference_3_2_0; }

		//EString
		public RuleCall getIncomingEdgesKEdgeEStringParserRuleCall_3_2_0_1() { return cIncomingEdgesKEdgeEStringParserRuleCall_3_2_0_1; }

		//("," incomingEdges+=[KEdge|EString])*
		public Group getGroup_3_3() { return cGroup_3_3; }

		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }

		//incomingEdges+=[KEdge|EString]
		public Assignment getIncomingEdgesAssignment_3_3_1() { return cIncomingEdgesAssignment_3_3_1; }

		//[KEdge|EString]
		public CrossReference getIncomingEdgesKEdgeCrossReference_3_3_1_0() { return cIncomingEdgesKEdgeCrossReference_3_3_1_0; }

		//EString
		public RuleCall getIncomingEdgesKEdgeEStringParserRuleCall_3_3_1_0_1() { return cIncomingEdgesKEdgeEStringParserRuleCall_3_3_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_3_4() { return cRightParenthesisKeyword_3_4; }

		//("data" "{" data+=KGraphData ("," data+=KGraphData)* "}")?
		public Group getGroup_4() { return cGroup_4; }

		//"data"
		public Keyword getDataKeyword_4_0() { return cDataKeyword_4_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }

		//data+=KGraphData
		public Assignment getDataAssignment_4_2() { return cDataAssignment_4_2; }

		//KGraphData
		public RuleCall getDataKGraphDataParserRuleCall_4_2_0() { return cDataKGraphDataParserRuleCall_4_2_0; }

		//("," data+=KGraphData)*
		public Group getGroup_4_3() { return cGroup_4_3; }

		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }

		//data+=KGraphData
		public Assignment getDataAssignment_4_3_1() { return cDataAssignment_4_3_1; }

		//KGraphData
		public RuleCall getDataKGraphDataParserRuleCall_4_3_1_0() { return cDataKGraphDataParserRuleCall_4_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }

		//("labels" "{" labels+=KLabel ("," labels+=KLabel)* "}")?
		public Group getGroup_5() { return cGroup_5; }

		//"labels"
		public Keyword getLabelsKeyword_5_0() { return cLabelsKeyword_5_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }

		//labels+=KLabel
		public Assignment getLabelsAssignment_5_2() { return cLabelsAssignment_5_2; }

		//KLabel
		public RuleCall getLabelsKLabelParserRuleCall_5_2_0() { return cLabelsKLabelParserRuleCall_5_2_0; }

		//("," labels+=KLabel)*
		public Group getGroup_5_3() { return cGroup_5_3; }

		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }

		//labels+=KLabel
		public Assignment getLabelsAssignment_5_3_1() { return cLabelsAssignment_5_3_1; }

		//KLabel
		public RuleCall getLabelsKLabelParserRuleCall_5_3_1_0() { return cLabelsKLabelParserRuleCall_5_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }

		//("children" "{" children+=KNode ("," children+=KNode)* "}")?
		public Group getGroup_6() { return cGroup_6; }

		//"children"
		public Keyword getChildrenKeyword_6_0() { return cChildrenKeyword_6_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }

		//children+=KNode
		public Assignment getChildrenAssignment_6_2() { return cChildrenAssignment_6_2; }

		//KNode
		public RuleCall getChildrenKNodeParserRuleCall_6_2_0() { return cChildrenKNodeParserRuleCall_6_2_0; }

		//("," children+=KNode)*
		public Group getGroup_6_3() { return cGroup_6_3; }

		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }

		//children+=KNode
		public Assignment getChildrenAssignment_6_3_1() { return cChildrenAssignment_6_3_1; }

		//KNode
		public RuleCall getChildrenKNodeParserRuleCall_6_3_1_0() { return cChildrenKNodeParserRuleCall_6_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }

		//("ports" "{" ports+=KPort ("," ports+=KPort)* "}")?
		public Group getGroup_7() { return cGroup_7; }

		//"ports"
		public Keyword getPortsKeyword_7_0() { return cPortsKeyword_7_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }

		//ports+=KPort
		public Assignment getPortsAssignment_7_2() { return cPortsAssignment_7_2; }

		//KPort
		public RuleCall getPortsKPortParserRuleCall_7_2_0() { return cPortsKPortParserRuleCall_7_2_0; }

		//("," ports+=KPort)*
		public Group getGroup_7_3() { return cGroup_7_3; }

		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }

		//ports+=KPort
		public Assignment getPortsAssignment_7_3_1() { return cPortsAssignment_7_3_1; }

		//KPort
		public RuleCall getPortsKPortParserRuleCall_7_3_1_0() { return cPortsKPortParserRuleCall_7_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }

		//("outgoingEdges" "{" outgoingEdges+=KEdge ("," outgoingEdges+=KEdge)* "}")?
		public Group getGroup_8() { return cGroup_8; }

		//"outgoingEdges"
		public Keyword getOutgoingEdgesKeyword_8_0() { return cOutgoingEdgesKeyword_8_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_8_1() { return cLeftCurlyBracketKeyword_8_1; }

		//outgoingEdges+=KEdge
		public Assignment getOutgoingEdgesAssignment_8_2() { return cOutgoingEdgesAssignment_8_2; }

		//KEdge
		public RuleCall getOutgoingEdgesKEdgeParserRuleCall_8_2_0() { return cOutgoingEdgesKEdgeParserRuleCall_8_2_0; }

		//("," outgoingEdges+=KEdge)*
		public Group getGroup_8_3() { return cGroup_8_3; }

		//","
		public Keyword getCommaKeyword_8_3_0() { return cCommaKeyword_8_3_0; }

		//outgoingEdges+=KEdge
		public Assignment getOutgoingEdgesAssignment_8_3_1() { return cOutgoingEdgesAssignment_8_3_1; }

		//KEdge
		public RuleCall getOutgoingEdgesKEdgeParserRuleCall_8_3_1_0() { return cOutgoingEdgesKEdgeParserRuleCall_8_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8_4() { return cRightCurlyBracketKeyword_8_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}

	public class KGraphDataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "KGraphData");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cKRenderingParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cKShapeLayoutParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cKEdgeLayoutParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//// Error marker is a false positive; generation works anyway!
		//KGraphData:
		//	KRendering | KShapeLayout | KEdgeLayout;
		public ParserRule getRule() { return rule; }

		//KRendering | KShapeLayout | KEdgeLayout
		public Alternatives getAlternatives() { return cAlternatives; }

		//KRendering
		public RuleCall getKRenderingParserRuleCall_0() { return cKRenderingParserRuleCall_0; }

		//KShapeLayout
		public RuleCall getKShapeLayoutParserRuleCall_1() { return cKShapeLayoutParserRuleCall_1; }

		//KEdgeLayout
		public RuleCall getKEdgeLayoutParserRuleCall_2() { return cKEdgeLayoutParserRuleCall_2; }
	}

	public class KLabelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "KLabel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cKLabelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cTextKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTextAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTextEStringParserRuleCall_3_0 = (RuleCall)cTextAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDataKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cDataAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cDataKGraphDataParserRuleCall_4_2_0 = (RuleCall)cDataAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cDataAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cDataKGraphDataParserRuleCall_4_3_1_0 = (RuleCall)cDataAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		////KGraphData returns KGraphData:
		////	{KGraphData}
		////	'KGraphData'
		////	'{'
		////		('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
		////    '}';
		//KLabel:
		//	"KLabel" "{" "text" text=EString ("data" "{" data+=KGraphData ("," data+=KGraphData)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//"KLabel" "{" "text" text=EString ("data" "{" data+=KGraphData ("," data+=KGraphData)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//"KLabel"
		public Keyword getKLabelKeyword_0() { return cKLabelKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"text"
		public Keyword getTextKeyword_2() { return cTextKeyword_2; }

		//text=EString
		public Assignment getTextAssignment_3() { return cTextAssignment_3; }

		//EString
		public RuleCall getTextEStringParserRuleCall_3_0() { return cTextEStringParserRuleCall_3_0; }

		//("data" "{" data+=KGraphData ("," data+=KGraphData)* "}")?
		public Group getGroup_4() { return cGroup_4; }

		//"data"
		public Keyword getDataKeyword_4_0() { return cDataKeyword_4_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }

		//data+=KGraphData
		public Assignment getDataAssignment_4_2() { return cDataAssignment_4_2; }

		//KGraphData
		public RuleCall getDataKGraphDataParserRuleCall_4_2_0() { return cDataKGraphDataParserRuleCall_4_2_0; }

		//("," data+=KGraphData)*
		public Group getGroup_4_3() { return cGroup_4_3; }

		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }

		//data+=KGraphData
		public Assignment getDataAssignment_4_3_1() { return cDataAssignment_4_3_1; }

		//KGraphData
		public RuleCall getDataKGraphDataParserRuleCall_4_3_1_0() { return cDataKGraphDataParserRuleCall_4_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class KPortElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "KPort");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cKPortAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cKPortKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cEdgesKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cEdgesAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final CrossReference cEdgesKEdgeCrossReference_3_2_0 = (CrossReference)cEdgesAssignment_3_2.eContents().get(0);
		private final RuleCall cEdgesKEdgeEStringParserRuleCall_3_2_0_1 = (RuleCall)cEdgesKEdgeCrossReference_3_2_0.eContents().get(1);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cEdgesAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final CrossReference cEdgesKEdgeCrossReference_3_3_1_0 = (CrossReference)cEdgesAssignment_3_3_1.eContents().get(0);
		private final RuleCall cEdgesKEdgeEStringParserRuleCall_3_3_1_0_1 = (RuleCall)cEdgesKEdgeCrossReference_3_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDataKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cDataAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cDataKGraphDataParserRuleCall_4_2_0 = (RuleCall)cDataAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cDataAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cDataKGraphDataParserRuleCall_4_3_1_0 = (RuleCall)cDataAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLabelsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cLabelsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cLabelsKLabelParserRuleCall_5_2_0 = (RuleCall)cLabelsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cLabelsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cLabelsKLabelParserRuleCall_5_3_1_0 = (RuleCall)cLabelsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//KPort:
		//	{KPort} "KPort" "{" ("edges" "(" edges+=[KEdge|EString] ("," edges+=[KEdge|EString])* ")")? ("data" "{"
		//	data+=KGraphData ("," data+=KGraphData)* "}")? ("labels" "{" labels+=KLabel ("," labels+=KLabel)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//{KPort} "KPort" "{" ("edges" "(" edges+=[KEdge|EString] ("," edges+=[KEdge|EString])* ")")? ("data" "{" data+=KGraphData
		//("," data+=KGraphData)* "}")? ("labels" "{" labels+=KLabel ("," labels+=KLabel)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{KPort}
		public Action getKPortAction_0() { return cKPortAction_0; }

		//"KPort"
		public Keyword getKPortKeyword_1() { return cKPortKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("edges" "(" edges+=[KEdge|EString] ("," edges+=[KEdge|EString])* ")")?
		public Group getGroup_3() { return cGroup_3; }

		//"edges"
		public Keyword getEdgesKeyword_3_0() { return cEdgesKeyword_3_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_3_1() { return cLeftParenthesisKeyword_3_1; }

		//edges+=[KEdge|EString]
		public Assignment getEdgesAssignment_3_2() { return cEdgesAssignment_3_2; }

		//[KEdge|EString]
		public CrossReference getEdgesKEdgeCrossReference_3_2_0() { return cEdgesKEdgeCrossReference_3_2_0; }

		//EString
		public RuleCall getEdgesKEdgeEStringParserRuleCall_3_2_0_1() { return cEdgesKEdgeEStringParserRuleCall_3_2_0_1; }

		//("," edges+=[KEdge|EString])*
		public Group getGroup_3_3() { return cGroup_3_3; }

		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }

		//edges+=[KEdge|EString]
		public Assignment getEdgesAssignment_3_3_1() { return cEdgesAssignment_3_3_1; }

		//[KEdge|EString]
		public CrossReference getEdgesKEdgeCrossReference_3_3_1_0() { return cEdgesKEdgeCrossReference_3_3_1_0; }

		//EString
		public RuleCall getEdgesKEdgeEStringParserRuleCall_3_3_1_0_1() { return cEdgesKEdgeEStringParserRuleCall_3_3_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_3_4() { return cRightParenthesisKeyword_3_4; }

		//("data" "{" data+=KGraphData ("," data+=KGraphData)* "}")?
		public Group getGroup_4() { return cGroup_4; }

		//"data"
		public Keyword getDataKeyword_4_0() { return cDataKeyword_4_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }

		//data+=KGraphData
		public Assignment getDataAssignment_4_2() { return cDataAssignment_4_2; }

		//KGraphData
		public RuleCall getDataKGraphDataParserRuleCall_4_2_0() { return cDataKGraphDataParserRuleCall_4_2_0; }

		//("," data+=KGraphData)*
		public Group getGroup_4_3() { return cGroup_4_3; }

		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }

		//data+=KGraphData
		public Assignment getDataAssignment_4_3_1() { return cDataAssignment_4_3_1; }

		//KGraphData
		public RuleCall getDataKGraphDataParserRuleCall_4_3_1_0() { return cDataKGraphDataParserRuleCall_4_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }

		//("labels" "{" labels+=KLabel ("," labels+=KLabel)* "}")?
		public Group getGroup_5() { return cGroup_5; }

		//"labels"
		public Keyword getLabelsKeyword_5_0() { return cLabelsKeyword_5_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }

		//labels+=KLabel
		public Assignment getLabelsAssignment_5_2() { return cLabelsAssignment_5_2; }

		//KLabel
		public RuleCall getLabelsKLabelParserRuleCall_5_2_0() { return cLabelsKLabelParserRuleCall_5_2_0; }

		//("," labels+=KLabel)*
		public Group getGroup_5_3() { return cGroup_5_3; }

		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }

		//labels+=KLabel
		public Assignment getLabelsAssignment_5_3_1() { return cLabelsAssignment_5_3_1; }

		//KLabel
		public RuleCall getLabelsKLabelParserRuleCall_5_3_1_0() { return cLabelsKLabelParserRuleCall_5_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class KEdgeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "KEdge");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cKEdgeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cTargetKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTargetAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cTargetKNodeCrossReference_3_0 = (CrossReference)cTargetAssignment_3.eContents().get(0);
		private final RuleCall cTargetKNodeEStringParserRuleCall_3_0_1 = (RuleCall)cTargetKNodeCrossReference_3_0.eContents().get(1);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cSourcePortKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cSourcePortAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cSourcePortKPortCrossReference_4_1_0 = (CrossReference)cSourcePortAssignment_4_1.eContents().get(0);
		private final RuleCall cSourcePortKPortEStringParserRuleCall_4_1_0_1 = (RuleCall)cSourcePortKPortCrossReference_4_1_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTargetPortKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTargetPortAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cTargetPortKPortCrossReference_5_1_0 = (CrossReference)cTargetPortAssignment_5_1.eContents().get(0);
		private final RuleCall cTargetPortKPortEStringParserRuleCall_5_1_0_1 = (RuleCall)cTargetPortKPortCrossReference_5_1_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cDataKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cDataAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cDataKGraphDataParserRuleCall_6_2_0 = (RuleCall)cDataAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cDataAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cDataKGraphDataParserRuleCall_6_3_1_0 = (RuleCall)cDataAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cLabelsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cLabelsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cLabelsKLabelParserRuleCall_7_2_0 = (RuleCall)cLabelsAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cLabelsAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cLabelsKLabelParserRuleCall_7_3_1_0 = (RuleCall)cLabelsAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//KEdge:
		//	"KEdge" "{" "target" target=[KNode|EString] ("sourcePort" sourcePort=[KPort|EString])? ("targetPort"
		//	targetPort=[KPort|EString])? ("data" "{" data+=KGraphData ("," data+=KGraphData)* "}")? ("labels" "{" labels+=KLabel
		//	("," labels+=KLabel)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//"KEdge" "{" "target" target=[KNode|EString] ("sourcePort" sourcePort=[KPort|EString])? ("targetPort"
		//targetPort=[KPort|EString])? ("data" "{" data+=KGraphData ("," data+=KGraphData)* "}")? ("labels" "{" labels+=KLabel
		//("," labels+=KLabel)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//"KEdge"
		public Keyword getKEdgeKeyword_0() { return cKEdgeKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"target"
		public Keyword getTargetKeyword_2() { return cTargetKeyword_2; }

		//target=[KNode|EString]
		public Assignment getTargetAssignment_3() { return cTargetAssignment_3; }

		//[KNode|EString]
		public CrossReference getTargetKNodeCrossReference_3_0() { return cTargetKNodeCrossReference_3_0; }

		//EString
		public RuleCall getTargetKNodeEStringParserRuleCall_3_0_1() { return cTargetKNodeEStringParserRuleCall_3_0_1; }

		//("sourcePort" sourcePort=[KPort|EString])?
		public Group getGroup_4() { return cGroup_4; }

		//"sourcePort"
		public Keyword getSourcePortKeyword_4_0() { return cSourcePortKeyword_4_0; }

		//sourcePort=[KPort|EString]
		public Assignment getSourcePortAssignment_4_1() { return cSourcePortAssignment_4_1; }

		//[KPort|EString]
		public CrossReference getSourcePortKPortCrossReference_4_1_0() { return cSourcePortKPortCrossReference_4_1_0; }

		//EString
		public RuleCall getSourcePortKPortEStringParserRuleCall_4_1_0_1() { return cSourcePortKPortEStringParserRuleCall_4_1_0_1; }

		//("targetPort" targetPort=[KPort|EString])?
		public Group getGroup_5() { return cGroup_5; }

		//"targetPort"
		public Keyword getTargetPortKeyword_5_0() { return cTargetPortKeyword_5_0; }

		//targetPort=[KPort|EString]
		public Assignment getTargetPortAssignment_5_1() { return cTargetPortAssignment_5_1; }

		//[KPort|EString]
		public CrossReference getTargetPortKPortCrossReference_5_1_0() { return cTargetPortKPortCrossReference_5_1_0; }

		//EString
		public RuleCall getTargetPortKPortEStringParserRuleCall_5_1_0_1() { return cTargetPortKPortEStringParserRuleCall_5_1_0_1; }

		//("data" "{" data+=KGraphData ("," data+=KGraphData)* "}")?
		public Group getGroup_6() { return cGroup_6; }

		//"data"
		public Keyword getDataKeyword_6_0() { return cDataKeyword_6_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }

		//data+=KGraphData
		public Assignment getDataAssignment_6_2() { return cDataAssignment_6_2; }

		//KGraphData
		public RuleCall getDataKGraphDataParserRuleCall_6_2_0() { return cDataKGraphDataParserRuleCall_6_2_0; }

		//("," data+=KGraphData)*
		public Group getGroup_6_3() { return cGroup_6_3; }

		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }

		//data+=KGraphData
		public Assignment getDataAssignment_6_3_1() { return cDataAssignment_6_3_1; }

		//KGraphData
		public RuleCall getDataKGraphDataParserRuleCall_6_3_1_0() { return cDataKGraphDataParserRuleCall_6_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }

		//("labels" "{" labels+=KLabel ("," labels+=KLabel)* "}")?
		public Group getGroup_7() { return cGroup_7; }

		//"labels"
		public Keyword getLabelsKeyword_7_0() { return cLabelsKeyword_7_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }

		//labels+=KLabel
		public Assignment getLabelsAssignment_7_2() { return cLabelsAssignment_7_2; }

		//KLabel
		public RuleCall getLabelsKLabelParserRuleCall_7_2_0() { return cLabelsKLabelParserRuleCall_7_2_0; }

		//("," labels+=KLabel)*
		public Group getGroup_7_3() { return cGroup_7_3; }

		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }

		//labels+=KLabel
		public Assignment getLabelsAssignment_7_3_1() { return cLabelsAssignment_7_3_1; }

		//KLabel
		public RuleCall getLabelsKLabelParserRuleCall_7_3_1_0() { return cLabelsKLabelParserRuleCall_7_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		////PersistentEntry returns PersistentEntry:
		////	'PersistentEntry'
		////	'{'
		////		'key' key=EString
		////		('value' value=EString)?
		////    '}';
		//EString returns ecore::EString:
		//	STRING | ID;
		public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	
	
	private KNodeElements pKNode;
	private KGraphDataElements pKGraphData;
	private KLabelElements pKLabel;
	private KPortElements pKPort;
	private KEdgeElements pKEdge;
	private EStringElements pEString;
	
	private final GrammarProvider grammarProvider;

	private KRenderingGrammarAccess gaKRendering;

	@Inject
	public KGraphGrammarAccess(GrammarProvider grammarProvider,
		KRenderingGrammarAccess gaKRendering) {
		this.grammarProvider = grammarProvider;
		this.gaKRendering = gaKRendering;
	}
	
	public Grammar getGrammar() {	
		return grammarProvider.getGrammar(this);
	}
	

	public KRenderingGrammarAccess getKRenderingGrammarAccess() {
		return gaKRendering;
	}

	
	//KNode:
	//	{KNode} "KNode" "{" ("incomingEdges" "(" incomingEdges+=[KEdge|EString] ("," incomingEdges+=[KEdge|EString])* ")")?
	//	("data" "{" data+=KGraphData ("," data+=KGraphData)* "}")? ("labels" "{" labels+=KLabel ("," labels+=KLabel)* "}")?
	//	("children" "{" children+=KNode ("," children+=KNode)* "}")? ("ports" "{" ports+=KPort ("," ports+=KPort)* "}")?
	//	("outgoingEdges" "{" outgoingEdges+=KEdge ("," outgoingEdges+=KEdge)* "}")? "}";
	public KNodeElements getKNodeAccess() {
		return (pKNode != null) ? pKNode : (pKNode = new KNodeElements());
	}
	
	public ParserRule getKNodeRule() {
		return getKNodeAccess().getRule();
	}

	//// Error marker is a false positive; generation works anyway!
	//KGraphData:
	//	KRendering | KShapeLayout | KEdgeLayout;
	public KGraphDataElements getKGraphDataAccess() {
		return (pKGraphData != null) ? pKGraphData : (pKGraphData = new KGraphDataElements());
	}
	
	public ParserRule getKGraphDataRule() {
		return getKGraphDataAccess().getRule();
	}

	////KGraphData returns KGraphData:
	////	{KGraphData}
	////	'KGraphData'
	////	'{'
	////		('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	////    '}';
	//KLabel:
	//	"KLabel" "{" "text" text=EString ("data" "{" data+=KGraphData ("," data+=KGraphData)* "}")? "}";
	public KLabelElements getKLabelAccess() {
		return (pKLabel != null) ? pKLabel : (pKLabel = new KLabelElements());
	}
	
	public ParserRule getKLabelRule() {
		return getKLabelAccess().getRule();
	}

	//KPort:
	//	{KPort} "KPort" "{" ("edges" "(" edges+=[KEdge|EString] ("," edges+=[KEdge|EString])* ")")? ("data" "{"
	//	data+=KGraphData ("," data+=KGraphData)* "}")? ("labels" "{" labels+=KLabel ("," labels+=KLabel)* "}")? "}";
	public KPortElements getKPortAccess() {
		return (pKPort != null) ? pKPort : (pKPort = new KPortElements());
	}
	
	public ParserRule getKPortRule() {
		return getKPortAccess().getRule();
	}

	//KEdge:
	//	"KEdge" "{" "target" target=[KNode|EString] ("sourcePort" sourcePort=[KPort|EString])? ("targetPort"
	//	targetPort=[KPort|EString])? ("data" "{" data+=KGraphData ("," data+=KGraphData)* "}")? ("labels" "{" labels+=KLabel
	//	("," labels+=KLabel)* "}")? "}";
	public KEdgeElements getKEdgeAccess() {
		return (pKEdge != null) ? pKEdge : (pKEdge = new KEdgeElements());
	}
	
	public ParserRule getKEdgeRule() {
		return getKEdgeAccess().getRule();
	}

	////PersistentEntry returns PersistentEntry:
	////	'PersistentEntry'
	////	'{'
	////		'key' key=EString
	////		('value' value=EString)?
	////    '}';
	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return (pEString != null) ? pEString : (pEString = new EStringElements());
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//KRenderingLibrary:
	//	{KRenderingLibrary} "KRenderingLibrary" "{" // ('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	//	("renderings" "{" renderings+=KRendering ("," renderings+=KRendering)* "}")? "}";
	public KRenderingGrammarAccess.KRenderingLibraryElements getKRenderingLibraryAccess() {
		return gaKRendering.getKRenderingLibraryAccess();
	}
	
	public ParserRule getKRenderingLibraryRule() {
		return getKRenderingLibraryAccess().getRule();
	}

	//KRendering:
	//	KEllipse | KRectangle | KRoundedRectangle | KPolyline_Impl | KPolygon | KImage | KArc | KRenderingRef | KChildArea |
	//	KText | KCustomRendering | KSpline;
	public KRenderingGrammarAccess.KRenderingElements getKRenderingAccess() {
		return gaKRendering.getKRenderingAccess();
	}
	
	public ParserRule getKRenderingRule() {
		return getKRenderingAccess().getRule();
	}

	//KPlacementData:
	//	KDecoratorPlacementData | KGridPlacementData | KStackPlacementData | KDirectPlacementData | KPolylinePlacementData;
	public KRenderingGrammarAccess.KPlacementDataElements getKPlacementDataAccess() {
		return gaKRendering.getKPlacementDataAccess();
	}
	
	public ParserRule getKPlacementDataRule() {
		return getKPlacementDataAccess().getRule();
	}

	//KStyle:
	//	KStyle_Impl | KForegroundColor | KBackgroundColor | KLineWidth | KVisibility | KLineStyle | KVerticalAlignment |
	//	KHorizontalAlignment;
	public KRenderingGrammarAccess.KStyleElements getKStyleAccess() {
		return gaKRendering.getKStyleAccess();
	}
	
	public ParserRule getKStyleRule() {
		return getKStyleAccess().getRule();
	}

	//KPlacement:
	//	KGridPlacement | KStackPlacement;
	public KRenderingGrammarAccess.KPlacementElements getKPlacementAccess() {
		return gaKRendering.getKPlacementAccess();
	}
	
	public ParserRule getKPlacementRule() {
		return getKPlacementAccess().getRule();
	}

	//KXPosition:
	//	KLeftPosition | KRightPosition;
	public KRenderingGrammarAccess.KXPositionElements getKXPositionAccess() {
		return gaKRendering.getKXPositionAccess();
	}
	
	public ParserRule getKXPositionRule() {
		return getKXPositionAccess().getRule();
	}

	//KYPosition:
	//	KTopPosition | KBottomPosition;
	public KRenderingGrammarAccess.KYPositionElements getKYPositionAccess() {
		return gaKRendering.getKYPositionAccess();
	}
	
	public ParserRule getKYPositionRule() {
		return getKYPositionAccess().getRule();
	}

	//PersistentEntry returns kgraph::PersistentEntry:
	//	"PersistentEntry" "{" "key" key=EString ("value" value=EString)? "}";
	public KRenderingGrammarAccess.PersistentEntryElements getPersistentEntryAccess() {
		return gaKRendering.getPersistentEntryAccess();
	}
	
	public ParserRule getPersistentEntryRule() {
		return getPersistentEntryAccess().getRule();
	}

	//KRenderingRef:
	//	"KRenderingRef" "{" ("references" "(" references+=[KRenderingRef|EString] ("," references+=[KRenderingRef|EString])*
	//	")")? "rendering" rendering=[KRendering|EString] //		('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	//	("placementData" placementData=KPlacementData)? ("styles" "{" styles+=KStyle ("," styles+=KStyle)* "}")? "}";
	public KRenderingGrammarAccess.KRenderingRefElements getKRenderingRefAccess() {
		return gaKRendering.getKRenderingRefAccess();
	}
	
	public ParserRule getKRenderingRefRule() {
		return getKRenderingRefAccess().getRule();
	}

	//KStyle_Impl returns KStyle:
	//	propagateToChildren?="propagateToChildren" "KStyle";
	public KRenderingGrammarAccess.KStyle_ImplElements getKStyle_ImplAccess() {
		return gaKRendering.getKStyle_ImplAccess();
	}
	
	public ParserRule getKStyle_ImplRule() {
		return getKStyle_ImplAccess().getRule();
	}

	//KEllipse:
	//	{KEllipse} "KEllipse" "{" ("references" "(" references+=[KRenderingRef|EString] (","
	//	references+=[KRenderingRef|EString])* ")")? //		('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	//	("placementData" placementData=KPlacementData)? ("styles" "{" styles+=KStyle ("," styles+=KStyle)* "}")? ("children"
	//	"{" children+=KRendering ("," children+=KRendering)* "}")? ("childPlacement" childPlacement=KPlacement)? "}";
	public KRenderingGrammarAccess.KEllipseElements getKEllipseAccess() {
		return gaKRendering.getKEllipseAccess();
	}
	
	public ParserRule getKEllipseRule() {
		return getKEllipseAccess().getRule();
	}

	//KRectangle:
	//	{KRectangle} "KRectangle" "{" ("references" "(" references+=[KRenderingRef|EString] (","
	//	references+=[KRenderingRef|EString])* ")")? //		('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	//	("placementData" placementData=KPlacementData)? ("styles" "{" styles+=KStyle ("," styles+=KStyle)* "}")? ("children"
	//	"{" children+=KRendering ("," children+=KRendering)* "}")? ("childPlacement" childPlacement=KPlacement)? "}";
	public KRenderingGrammarAccess.KRectangleElements getKRectangleAccess() {
		return gaKRendering.getKRectangleAccess();
	}
	
	public ParserRule getKRectangleRule() {
		return getKRectangleAccess().getRule();
	}

	//KRoundedRectangle:
	//	"KRoundedRectangle" "{" "cornerWidth" cornerWidth=EFloat "cornerHeight" cornerHeight=EFloat ("references" "("
	//	references+=[KRenderingRef|EString] ("," references+=[KRenderingRef|EString])* ")")? //		('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	//	("placementData" placementData=KPlacementData)? ("styles" "{" styles+=KStyle ("," styles+=KStyle)* "}")? ("children"
	//	"{" children+=KRendering ("," children+=KRendering)* "}")? ("childPlacement" childPlacement=KPlacement)? "}";
	public KRenderingGrammarAccess.KRoundedRectangleElements getKRoundedRectangleAccess() {
		return gaKRendering.getKRoundedRectangleAccess();
	}
	
	public ParserRule getKRoundedRectangleRule() {
		return getKRoundedRectangleAccess().getRule();
	}

	//KPolyline_Impl returns KPolyline:
	//	{KPolyline} "KPolyline" "{" ("references" "(" references+=[KRenderingRef|EString] (","
	//	references+=[KRenderingRef|EString])* ")")? //		('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	//	("placementData" placementData=KPlacementData)? ("styles" "{" styles+=KStyle ("," styles+=KStyle)* "}")? ("children"
	//	"{" children+=KRendering ("," children+=KRendering)* "}")? ("childPlacement" childPlacement=KPlacement)? "}";
	public KRenderingGrammarAccess.KPolyline_ImplElements getKPolyline_ImplAccess() {
		return gaKRendering.getKPolyline_ImplAccess();
	}
	
	public ParserRule getKPolyline_ImplRule() {
		return getKPolyline_ImplAccess().getRule();
	}

	//KPolygon:
	//	{KPolygon} "KPolygon" "{" ("references" "(" references+=[KRenderingRef|EString] (","
	//	references+=[KRenderingRef|EString])* ")")? //		('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	//	("placementData" placementData=KPlacementData)? ("styles" "{" styles+=KStyle ("," styles+=KStyle)* "}")? ("children"
	//	"{" children+=KRendering ("," children+=KRendering)* "}")? ("childPlacement" childPlacement=KPlacement)? "}";
	public KRenderingGrammarAccess.KPolygonElements getKPolygonAccess() {
		return gaKRendering.getKPolygonAccess();
	}
	
	public ParserRule getKPolygonRule() {
		return getKPolygonAccess().getRule();
	}

	//KImage:
	//	"KImage" "{" "bundleName" bundleName=EString "imagePath" imagePath=EString ("references" "("
	//	references+=[KRenderingRef|EString] ("," references+=[KRenderingRef|EString])* ")")? //		('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	//	("placementData" placementData=KPlacementData)? ("styles" "{" styles+=KStyle ("," styles+=KStyle)* "}")? ("children"
	//	"{" children+=KRendering ("," children+=KRendering)* "}")? ("childPlacement" childPlacement=KPlacement)? "}";
	public KRenderingGrammarAccess.KImageElements getKImageAccess() {
		return gaKRendering.getKImageAccess();
	}
	
	public ParserRule getKImageRule() {
		return getKImageAccess().getRule();
	}

	//KArc:
	//	{KArc} "KArc" "{" ("startAngle" startAngle=EFloat)? ("arcAngle" arcAngle=EFloat)? ("references" "("
	//	references+=[KRenderingRef|EString] ("," references+=[KRenderingRef|EString])* ")")? //		('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	//	("placementData" placementData=KPlacementData)? ("styles" "{" styles+=KStyle ("," styles+=KStyle)* "}")? ("children"
	//	"{" children+=KRendering ("," children+=KRendering)* "}")? ("childPlacement" childPlacement=KPlacement)? "}";
	public KRenderingGrammarAccess.KArcElements getKArcAccess() {
		return gaKRendering.getKArcAccess();
	}
	
	public ParserRule getKArcRule() {
		return getKArcAccess().getRule();
	}

	//KChildArea:
	//	{KChildArea} "KChildArea" "{" ("references" "(" references+=[KRenderingRef|EString] (","
	//	references+=[KRenderingRef|EString])* ")")? //		('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	//	("placementData" placementData=KPlacementData)? ("styles" "{" styles+=KStyle ("," styles+=KStyle)* "}")? "}";
	public KRenderingGrammarAccess.KChildAreaElements getKChildAreaAccess() {
		return gaKRendering.getKChildAreaAccess();
	}
	
	public ParserRule getKChildAreaRule() {
		return getKChildAreaAccess().getRule();
	}

	//KText:
	//	clip?="clip" "KText" "{" ("text" text=EString)? ("references" "(" references+=[KRenderingRef|EString] (","
	//	references+=[KRenderingRef|EString])* ")")? //		('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	//	("placementData" placementData=KPlacementData)? ("styles" "{" styles+=KStyle ("," styles+=KStyle)* "}")? ("children"
	//	"{" children+=KRendering ("," children+=KRendering)* "}")? ("childPlacement" childPlacement=KPlacement)? "}";
	public KRenderingGrammarAccess.KTextElements getKTextAccess() {
		return gaKRendering.getKTextAccess();
	}
	
	public ParserRule getKTextRule() {
		return getKTextAccess().getRule();
	}

	//KCustomRendering:
	//	"KCustomRendering" "{" "className" className=EString "bundleName" bundleName=EString ("references" "("
	//	references+=[KRenderingRef|EString] ("," references+=[KRenderingRef|EString])* ")")? //		('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	//	("placementData" placementData=KPlacementData)? ("styles" "{" styles+=KStyle ("," styles+=KStyle)* "}")? ("children"
	//	"{" children+=KRendering ("," children+=KRendering)* "}")? ("childPlacement" childPlacement=KPlacement)? "}";
	public KRenderingGrammarAccess.KCustomRenderingElements getKCustomRenderingAccess() {
		return gaKRendering.getKCustomRenderingAccess();
	}
	
	public ParserRule getKCustomRenderingRule() {
		return getKCustomRenderingAccess().getRule();
	}

	//KSpline:
	//	{KSpline} "KSpline" "{" ("references" "(" references+=[KRenderingRef|EString] (","
	//	references+=[KRenderingRef|EString])* ")")? //		('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	//	("placementData" placementData=KPlacementData)? ("styles" "{" styles+=KStyle ("," styles+=KStyle)* "}")? ("children"
	//	"{" children+=KRendering ("," children+=KRendering)* "}")? ("childPlacement" childPlacement=KPlacement)? "}";
	public KRenderingGrammarAccess.KSplineElements getKSplineAccess() {
		return gaKRendering.getKSplineAccess();
	}
	
	public ParserRule getKSplineRule() {
		return getKSplineAccess().getRule();
	}

	//KDecoratorPlacementData:
	//	relative?="relative" "KDecoratorPlacementData" "{" "location" location=EFloat ("xOffset" xOffset=EFloat)? ("yOffset"
	//	yOffset=EFloat)? "}";
	public KRenderingGrammarAccess.KDecoratorPlacementDataElements getKDecoratorPlacementDataAccess() {
		return gaKRendering.getKDecoratorPlacementDataAccess();
	}
	
	public ParserRule getKDecoratorPlacementDataRule() {
		return getKDecoratorPlacementDataAccess().getRule();
	}

	//KGridPlacementData:
	//	"KGridPlacementData" "{" "widthHint" widthHint=EFloat "heightHint" heightHint=EFloat "horizontalIndent"
	//	horizontalIndent=EFloat "verticalIndent" verticalIndent=EFloat "}";
	public KRenderingGrammarAccess.KGridPlacementDataElements getKGridPlacementDataAccess() {
		return gaKRendering.getKGridPlacementDataAccess();
	}
	
	public ParserRule getKGridPlacementDataRule() {
		return getKGridPlacementDataAccess().getRule();
	}

	//KStackPlacementData:
	//	"KStackPlacementData" "{" "insetRight" insetRight=EFloat "insetBottom" insetBottom=EFloat "insetLeft" insetLeft=EFloat
	//	"insetTop" insetTop=EFloat "}";
	public KRenderingGrammarAccess.KStackPlacementDataElements getKStackPlacementDataAccess() {
		return gaKRendering.getKStackPlacementDataAccess();
	}
	
	public ParserRule getKStackPlacementDataRule() {
		return getKStackPlacementDataAccess().getRule();
	}

	//KDirectPlacementData:
	//	"KDirectPlacementData" "{" "topLeft" topLeft=KPosition "bottomRight" bottomRight=KPosition "}";
	public KRenderingGrammarAccess.KDirectPlacementDataElements getKDirectPlacementDataAccess() {
		return gaKRendering.getKDirectPlacementDataAccess();
	}
	
	public ParserRule getKDirectPlacementDataRule() {
		return getKDirectPlacementDataAccess().getRule();
	}

	//KPolylinePlacementData:
	//	"KPolylinePlacementData" "{" "points" "{" points+=KPosition ("," points+=KPosition)* "}" "}";
	public KRenderingGrammarAccess.KPolylinePlacementDataElements getKPolylinePlacementDataAccess() {
		return gaKRendering.getKPolylinePlacementDataAccess();
	}
	
	public ParserRule getKPolylinePlacementDataRule() {
		return getKPolylinePlacementDataAccess().getRule();
	}

	//EFloat returns ecore::EFloat:
	//	"-"? INT? "." INT (("E" | "e") "-"? INT)?;
	public KRenderingGrammarAccess.EFloatElements getEFloatAccess() {
		return gaKRendering.getEFloatAccess();
	}
	
	public ParserRule getEFloatRule() {
		return getEFloatAccess().getRule();
	}

	//EBoolean returns ecore::EBoolean:
	//	"true" | "false";
	public KRenderingGrammarAccess.EBooleanElements getEBooleanAccess() {
		return gaKRendering.getEBooleanAccess();
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}

	//KPosition:
	//	"KPosition" "{" "x" x=KXPosition "y" y=KYPosition "}";
	public KRenderingGrammarAccess.KPositionElements getKPositionAccess() {
		return gaKRendering.getKPositionAccess();
	}
	
	public ParserRule getKPositionRule() {
		return getKPositionAccess().getRule();
	}

	//KLeftPosition:
	//	{KLeftPosition} "KLeftPosition" "{" ("absolute" absolute=EFloat)? ("relative" relative=EFloat)? "}";
	public KRenderingGrammarAccess.KLeftPositionElements getKLeftPositionAccess() {
		return gaKRendering.getKLeftPositionAccess();
	}
	
	public ParserRule getKLeftPositionRule() {
		return getKLeftPositionAccess().getRule();
	}

	//KRightPosition:
	//	{KRightPosition} "KRightPosition" "{" ("absolute" absolute=EFloat)? ("relative" relative=EFloat)? "}";
	public KRenderingGrammarAccess.KRightPositionElements getKRightPositionAccess() {
		return gaKRendering.getKRightPositionAccess();
	}
	
	public ParserRule getKRightPositionRule() {
		return getKRightPositionAccess().getRule();
	}

	//KTopPosition:
	//	{KTopPosition} "KTopPosition" "{" ("absolute" absolute=EFloat)? ("relative" relative=EFloat)? "}";
	public KRenderingGrammarAccess.KTopPositionElements getKTopPositionAccess() {
		return gaKRendering.getKTopPositionAccess();
	}
	
	public ParserRule getKTopPositionRule() {
		return getKTopPositionAccess().getRule();
	}

	//KBottomPosition:
	//	{KBottomPosition} "KBottomPosition" "{" ("absolute" absolute=EFloat)? ("relative" relative=EFloat)? "}";
	public KRenderingGrammarAccess.KBottomPositionElements getKBottomPositionAccess() {
		return gaKRendering.getKBottomPositionAccess();
	}
	
	public ParserRule getKBottomPositionRule() {
		return getKBottomPositionAccess().getRule();
	}

	//KForegroundColor:
	//	propagateToChildren?="propagateToChildren" "KForegroundColor" "{" "red" red=EInt "green" green=EInt "blue" blue=EInt
	//	"}";
	public KRenderingGrammarAccess.KForegroundColorElements getKForegroundColorAccess() {
		return gaKRendering.getKForegroundColorAccess();
	}
	
	public ParserRule getKForegroundColorRule() {
		return getKForegroundColorAccess().getRule();
	}

	//KBackgroundColor:
	//	propagateToChildren?="propagateToChildren" "KBackgroundColor" "{" "red" red=EInt "green" green=EInt "blue" blue=EInt
	//	"}";
	public KRenderingGrammarAccess.KBackgroundColorElements getKBackgroundColorAccess() {
		return gaKRendering.getKBackgroundColorAccess();
	}
	
	public ParserRule getKBackgroundColorRule() {
		return getKBackgroundColorAccess().getRule();
	}

	//KLineWidth:
	//	propagateToChildren?="propagateToChildren" "KLineWidth" "{" "lineWidth" lineWidth=EInt "}";
	public KRenderingGrammarAccess.KLineWidthElements getKLineWidthAccess() {
		return gaKRendering.getKLineWidthAccess();
	}
	
	public ParserRule getKLineWidthRule() {
		return getKLineWidthAccess().getRule();
	}

	//KVisibility:
	//	propagateToChildren?="propagateToChildren" lineVisible?="lineVisible" filled?="filled" "KVisibility";
	public KRenderingGrammarAccess.KVisibilityElements getKVisibilityAccess() {
		return gaKRendering.getKVisibilityAccess();
	}
	
	public ParserRule getKVisibilityRule() {
		return getKVisibilityAccess().getRule();
	}

	//KLineStyle:
	//	propagateToChildren?="propagateToChildren" "KLineStyle" "{" "lineStyle" lineStyle=LineStyle "}";
	public KRenderingGrammarAccess.KLineStyleElements getKLineStyleAccess() {
		return gaKRendering.getKLineStyleAccess();
	}
	
	public ParserRule getKLineStyleRule() {
		return getKLineStyleAccess().getRule();
	}

	//KVerticalAlignment:
	//	propagateToChildren?="propagateToChildren" "KVerticalAlignment" "{" "verticalAlignment"
	//	verticalAlignment=VerticalAlignment "}";
	public KRenderingGrammarAccess.KVerticalAlignmentElements getKVerticalAlignmentAccess() {
		return gaKRendering.getKVerticalAlignmentAccess();
	}
	
	public ParserRule getKVerticalAlignmentRule() {
		return getKVerticalAlignmentAccess().getRule();
	}

	//KHorizontalAlignment:
	//	propagateToChildren?="propagateToChildren" "KHorizontalAlignment" "{" "horizontalAlignment"
	//	horizontalAlignment=HorizontalAlignment "}";
	public KRenderingGrammarAccess.KHorizontalAlignmentElements getKHorizontalAlignmentAccess() {
		return gaKRendering.getKHorizontalAlignmentAccess();
	}
	
	public ParserRule getKHorizontalAlignmentRule() {
		return getKHorizontalAlignmentAccess().getRule();
	}

	//EInt returns ecore::EInt:
	//	"-"? INT;
	public KRenderingGrammarAccess.EIntElements getEIntAccess() {
		return gaKRendering.getEIntAccess();
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}

	//enum LineStyle:
	//	SOLID | DASH | DOT | DASHDOT | DASHDOTDOT;
	public KRenderingGrammarAccess.LineStyleElements getLineStyleAccess() {
		return gaKRendering.getLineStyleAccess();
	}
	
	public EnumRule getLineStyleRule() {
		return getLineStyleAccess().getRule();
	}

	//enum VerticalAlignment:
	//	TOP | CENTER | BOTTOM;
	public KRenderingGrammarAccess.VerticalAlignmentElements getVerticalAlignmentAccess() {
		return gaKRendering.getVerticalAlignmentAccess();
	}
	
	public EnumRule getVerticalAlignmentRule() {
		return getVerticalAlignmentAccess().getRule();
	}

	//enum HorizontalAlignment:
	//	LEFT | CENTER | RIGHT;
	public KRenderingGrammarAccess.HorizontalAlignmentElements getHorizontalAlignmentAccess() {
		return gaKRendering.getHorizontalAlignmentAccess();
	}
	
	public EnumRule getHorizontalAlignmentRule() {
		return getHorizontalAlignmentAccess().getRule();
	}

	//KGridPlacement:
	//	"KGridPlacement" "{" "numColumns" numColumns=EInt "}";
	public KRenderingGrammarAccess.KGridPlacementElements getKGridPlacementAccess() {
		return gaKRendering.getKGridPlacementAccess();
	}
	
	public ParserRule getKGridPlacementRule() {
		return getKGridPlacementAccess().getRule();
	}

	//KStackPlacement:
	//	{KStackPlacement} "KStackPlacement";
	public KRenderingGrammarAccess.KStackPlacementElements getKStackPlacementAccess() {
		return gaKRendering.getKStackPlacementAccess();
	}
	
	public ParserRule getKStackPlacementRule() {
		return getKStackPlacementAccess().getRule();
	}

	//KShapeLayout:
	//	{KShapeLayout} "KShapeLayout" "{" ("xpos" xpos=EFloat)? ("ypos" ypos=EFloat)? ("width" width=EFloat)? ("height"
	//	height=EFloat)? //		('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	//	("insets" insets=KInsets)? "}";
	public KLayoutDataGrammarAccess.KShapeLayoutElements getKShapeLayoutAccess() {
		return gaKRendering.getKShapeLayoutAccess();
	}
	
	public ParserRule getKShapeLayoutRule() {
		return getKShapeLayoutAccess().getRule();
	}

	//KInsets:
	//	{KInsets} "KInsets" "{" ("top" top=EFloat)? ("bottom" bottom=EFloat)? ("left" left=EFloat)? ("right" right=EFloat)?
	//	"}";
	public KLayoutDataGrammarAccess.KInsetsElements getKInsetsAccess() {
		return gaKRendering.getKInsetsAccess();
	}
	
	public ParserRule getKInsetsRule() {
		return getKInsetsAccess().getRule();
	}

	//KEdgeLayout:
	//	"KEdgeLayout" "{" //		('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	//	("bendPoints" "{" bendPoints+=KPoint ("," bendPoints+=KPoint)* "}")? "sourcePoint" sourcePoint=KPoint "targetPoint"
	//	targetPoint=KPoint "}";
	public KLayoutDataGrammarAccess.KEdgeLayoutElements getKEdgeLayoutAccess() {
		return gaKRendering.getKEdgeLayoutAccess();
	}
	
	public ParserRule getKEdgeLayoutRule() {
		return getKEdgeLayoutAccess().getRule();
	}

	////PersistentEntry returns kgraph::PersistentEntry:
	////	'PersistentEntry'
	////	'{'
	////		'key' key=EString
	////		('value' value=EString)?
	////    '}';
	//KPoint:
	//	{KPoint} "KPoint" "{" ("x" x=EFloat)? ("y" y=EFloat)? "}";
	public KLayoutDataGrammarAccess.KPointElements getKPointAccess() {
		return gaKRendering.getKPointAccess();
	}
	
	public ParserRule getKPointRule() {
		return getKPointAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaKRendering.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaKRendering.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaKRendering.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaKRendering.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaKRendering.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaKRendering.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaKRendering.getANY_OTHERRule();
	} 
}
