/*
* generated by Xtext
*/

package de.cau.cs.kieler.core.kgraph.text.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import de.cau.cs.kieler.core.krendering.text.services.KRenderingGrammarAccess;
import de.cau.cs.kieler.kiml.klayoutdata.text.services.KLayoutDataGrammarAccess;

@Singleton
public class KGraphGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class KNodeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "KNode");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cKNodeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cKNodeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cPortsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cPortsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cPortsKPortParserRuleCall_3_1_0 = (RuleCall)cPortsAssignment_3_1.eContents().get(0);
		private final Group cGroup_3_2 = (Group)cGroup_3.eContents().get(2);
		private final Keyword cCommaKeyword_3_2_0 = (Keyword)cGroup_3_2.eContents().get(0);
		private final Assignment cPortsAssignment_3_2_1 = (Assignment)cGroup_3_2.eContents().get(1);
		private final RuleCall cPortsKPortParserRuleCall_3_2_1_0 = (RuleCall)cPortsAssignment_3_2_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDataKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cColonKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cDataAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cDataKGraphDataParserRuleCall_4_2_0 = (RuleCall)cDataAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cDataAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cDataKGraphDataParserRuleCall_4_3_1_0 = (RuleCall)cDataAssignment_4_3_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cChildrenKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cColonKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cChildrenAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cChildrenKNodeParserRuleCall_5_2_0 = (RuleCall)cChildrenAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cChildrenAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cChildrenKNodeParserRuleCall_5_3_1_0 = (RuleCall)cChildrenAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Assignment cOutgoingEdgesAssignment_7_0 = (Assignment)cGroup_7.eContents().get(0);
		private final RuleCall cOutgoingEdgesKEdgeParserRuleCall_7_0_0 = (RuleCall)cOutgoingEdgesAssignment_7_0.eContents().get(0);
		private final Group cGroup_7_1 = (Group)cGroup_7.eContents().get(1);
		private final Keyword cCommaKeyword_7_1_0 = (Keyword)cGroup_7_1.eContents().get(0);
		private final Assignment cOutgoingEdgesAssignment_7_1_1 = (Assignment)cGroup_7_1.eContents().get(1);
		private final RuleCall cOutgoingEdgesKEdgeParserRuleCall_7_1_1_0 = (RuleCall)cOutgoingEdgesAssignment_7_1_1.eContents().get(0);
		
		//KNode: //	{KNode}
		////	'KNode'
		////	'{'
		////		('incomingEdges' '(' incomingEdges+=[KEdge|EString] ( "," incomingEdges+=[KEdge|EString])* ')' )?
		////		('data' '{' data+=KGraphData ( "," data+=KGraphData)* '}' )?
		////		('labels' '{' labels+=KLabel ( "," labels+=KLabel)* '}' )?
		////		('children' '{' children+=KNode ( "," children+=KNode)* '}' )?
		////		('ports' '{' ports+=KPort ( "," ports+=KPort)* '}' )?
		////		('outgoingEdges' '{' outgoingEdges+=KEdge ( "," outgoingEdges+=KEdge)* '}' )?
		////    '}';
		//	{KNode} "KNode" "{" ("ports" ports+=KPort ("," ports+=KPort)*)? ("data" ":" data+=KGraphData ("," data+=KGraphData)*)? //('labels' '{' labels+=KLabel ( "," labels+=KLabel)* '}' )?
		//	("children" ":" children+=KNode ("," children+=KNode)*)? "}" (outgoingEdges+=KEdge ("," outgoingEdges+=KEdge)*)?;
		public ParserRule getRule() { return rule; }

		////	{KNode}
		////	'KNode'
		////	'{'
		////		('incomingEdges' '(' incomingEdges+=[KEdge|EString] ( "," incomingEdges+=[KEdge|EString])* ')' )?
		////		('data' '{' data+=KGraphData ( "," data+=KGraphData)* '}' )?
		////		('labels' '{' labels+=KLabel ( "," labels+=KLabel)* '}' )?
		////		('children' '{' children+=KNode ( "," children+=KNode)* '}' )?
		////		('ports' '{' ports+=KPort ( "," ports+=KPort)* '}' )?
		////		('outgoingEdges' '{' outgoingEdges+=KEdge ( "," outgoingEdges+=KEdge)* '}' )?
		////    '}';
		//{KNode} "KNode" "{" ("ports" ports+=KPort ("," ports+=KPort)*)? ("data" ":" data+=KGraphData ("," data+=KGraphData)*)? //('labels' '{' labels+=KLabel ( "," labels+=KLabel)* '}' )?
		//("children" ":" children+=KNode ("," children+=KNode)*)? "}" (outgoingEdges+=KEdge ("," outgoingEdges+=KEdge)*)?
		public Group getGroup() { return cGroup; }

		////	{KNode}
		////	'KNode'
		////	'{'
		////		('incomingEdges' '(' incomingEdges+=[KEdge|EString] ( "," incomingEdges+=[KEdge|EString])* ')' )?
		////		('data' '{' data+=KGraphData ( "," data+=KGraphData)* '}' )?
		////		('labels' '{' labels+=KLabel ( "," labels+=KLabel)* '}' )?
		////		('children' '{' children+=KNode ( "," children+=KNode)* '}' )?
		////		('ports' '{' ports+=KPort ( "," ports+=KPort)* '}' )?
		////		('outgoingEdges' '{' outgoingEdges+=KEdge ( "," outgoingEdges+=KEdge)* '}' )?
		////    '}';
		//{KNode}
		public Action getKNodeAction_0() { return cKNodeAction_0; }

		//"KNode"
		public Keyword getKNodeKeyword_1() { return cKNodeKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("ports" ports+=KPort ("," ports+=KPort)*)?
		public Group getGroup_3() { return cGroup_3; }

		//"ports"
		public Keyword getPortsKeyword_3_0() { return cPortsKeyword_3_0; }

		//ports+=KPort
		public Assignment getPortsAssignment_3_1() { return cPortsAssignment_3_1; }

		//KPort
		public RuleCall getPortsKPortParserRuleCall_3_1_0() { return cPortsKPortParserRuleCall_3_1_0; }

		//("," ports+=KPort)*
		public Group getGroup_3_2() { return cGroup_3_2; }

		//","
		public Keyword getCommaKeyword_3_2_0() { return cCommaKeyword_3_2_0; }

		//ports+=KPort
		public Assignment getPortsAssignment_3_2_1() { return cPortsAssignment_3_2_1; }

		//KPort
		public RuleCall getPortsKPortParserRuleCall_3_2_1_0() { return cPortsKPortParserRuleCall_3_2_1_0; }

		//("data" ":" data+=KGraphData ("," data+=KGraphData)*)?
		public Group getGroup_4() { return cGroup_4; }

		//"data"
		public Keyword getDataKeyword_4_0() { return cDataKeyword_4_0; }

		//":"
		public Keyword getColonKeyword_4_1() { return cColonKeyword_4_1; }

		//data+=KGraphData
		public Assignment getDataAssignment_4_2() { return cDataAssignment_4_2; }

		//KGraphData
		public RuleCall getDataKGraphDataParserRuleCall_4_2_0() { return cDataKGraphDataParserRuleCall_4_2_0; }

		//("," data+=KGraphData)*
		public Group getGroup_4_3() { return cGroup_4_3; }

		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }

		//data+=KGraphData
		public Assignment getDataAssignment_4_3_1() { return cDataAssignment_4_3_1; }

		//KGraphData
		public RuleCall getDataKGraphDataParserRuleCall_4_3_1_0() { return cDataKGraphDataParserRuleCall_4_3_1_0; }

		//("children" ":" children+=KNode ("," children+=KNode)*)?
		public Group getGroup_5() { return cGroup_5; }

		//"children"
		public Keyword getChildrenKeyword_5_0() { return cChildrenKeyword_5_0; }

		//":"
		public Keyword getColonKeyword_5_1() { return cColonKeyword_5_1; }

		//children+=KNode
		public Assignment getChildrenAssignment_5_2() { return cChildrenAssignment_5_2; }

		//KNode
		public RuleCall getChildrenKNodeParserRuleCall_5_2_0() { return cChildrenKNodeParserRuleCall_5_2_0; }

		//("," children+=KNode)*
		public Group getGroup_5_3() { return cGroup_5_3; }

		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }

		//children+=KNode
		public Assignment getChildrenAssignment_5_3_1() { return cChildrenAssignment_5_3_1; }

		//KNode
		public RuleCall getChildrenKNodeParserRuleCall_5_3_1_0() { return cChildrenKNodeParserRuleCall_5_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }

		//(outgoingEdges+=KEdge ("," outgoingEdges+=KEdge)*)?
		public Group getGroup_7() { return cGroup_7; }

		//outgoingEdges+=KEdge
		public Assignment getOutgoingEdgesAssignment_7_0() { return cOutgoingEdgesAssignment_7_0; }

		//KEdge
		public RuleCall getOutgoingEdgesKEdgeParserRuleCall_7_0_0() { return cOutgoingEdgesKEdgeParserRuleCall_7_0_0; }

		//("," outgoingEdges+=KEdge)*
		public Group getGroup_7_1() { return cGroup_7_1; }

		//","
		public Keyword getCommaKeyword_7_1_0() { return cCommaKeyword_7_1_0; }

		//outgoingEdges+=KEdge
		public Assignment getOutgoingEdgesAssignment_7_1_1() { return cOutgoingEdgesAssignment_7_1_1; }

		//KEdge
		public RuleCall getOutgoingEdgesKEdgeParserRuleCall_7_1_1_0() { return cOutgoingEdgesKEdgeParserRuleCall_7_1_1_0; }
	}

	public class KLabelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "KLabel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cKLabelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTextAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTextEStringParserRuleCall_1_0 = (RuleCall)cTextAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDataKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cColonKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cDataAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cDataKGraphDataParserRuleCall_3_2_0 = (RuleCall)cDataAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cDataAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cDataKGraphDataParserRuleCall_3_3_1_0 = (RuleCall)cDataAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//KLabel: //	'KLabel'
		////	'{'
		////		'text' text=EString
		////		('data' '{' data+=KGraphData ( "," data+=KGraphData)* '}' )?
		////    '}';
		//	"KLabel" text=EString "{" ("data" ":" data+=KGraphData ("," data+=KGraphData)*)? "}";
		public ParserRule getRule() { return rule; }

		////	'KLabel'
		////	'{'
		////		'text' text=EString
		////		('data' '{' data+=KGraphData ( "," data+=KGraphData)* '}' )?
		////    '}';
		//"KLabel" text=EString "{" ("data" ":" data+=KGraphData ("," data+=KGraphData)*)? "}"
		public Group getGroup() { return cGroup; }

		////	'KLabel'
		////	'{'
		////		'text' text=EString
		////		('data' '{' data+=KGraphData ( "," data+=KGraphData)* '}' )?
		////    '}';
		//"KLabel"
		public Keyword getKLabelKeyword_0() { return cKLabelKeyword_0; }

		//text=EString
		public Assignment getTextAssignment_1() { return cTextAssignment_1; }

		//EString
		public RuleCall getTextEStringParserRuleCall_1_0() { return cTextEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("data" ":" data+=KGraphData ("," data+=KGraphData)*)?
		public Group getGroup_3() { return cGroup_3; }

		//"data"
		public Keyword getDataKeyword_3_0() { return cDataKeyword_3_0; }

		//":"
		public Keyword getColonKeyword_3_1() { return cColonKeyword_3_1; }

		//data+=KGraphData
		public Assignment getDataAssignment_3_2() { return cDataAssignment_3_2; }

		//KGraphData
		public RuleCall getDataKGraphDataParserRuleCall_3_2_0() { return cDataKGraphDataParserRuleCall_3_2_0; }

		//("," data+=KGraphData)*
		public Group getGroup_3_3() { return cGroup_3_3; }

		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }

		//data+=KGraphData
		public Assignment getDataAssignment_3_3_1() { return cDataAssignment_3_3_1; }

		//KGraphData
		public RuleCall getDataKGraphDataParserRuleCall_3_3_1_0() { return cDataKGraphDataParserRuleCall_3_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class KPortElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "KPort");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cKPortAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cKPortKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cEdgesKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cColonKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cEdgesAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final CrossReference cEdgesKEdgeCrossReference_3_2_0 = (CrossReference)cEdgesAssignment_3_2.eContents().get(0);
		private final RuleCall cEdgesKEdgeEStringParserRuleCall_3_2_0_1 = (RuleCall)cEdgesKEdgeCrossReference_3_2_0.eContents().get(1);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cEdgesAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final CrossReference cEdgesKEdgeCrossReference_3_3_1_0 = (CrossReference)cEdgesAssignment_3_3_1.eContents().get(0);
		private final RuleCall cEdgesKEdgeEStringParserRuleCall_3_3_1_0_1 = (RuleCall)cEdgesKEdgeCrossReference_3_3_1_0.eContents().get(1);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDataKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cColonKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cDataAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cDataKGraphDataParserRuleCall_4_2_0 = (RuleCall)cDataAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cDataAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cDataKGraphDataParserRuleCall_4_3_1_0 = (RuleCall)cDataAssignment_4_3_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLabelsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cColonKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cLabelsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cLabelsKLabelParserRuleCall_5_2_0 = (RuleCall)cLabelsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cLabelsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cLabelsKLabelParserRuleCall_5_3_1_0 = (RuleCall)cLabelsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//KPort: //	{KPort}
		////	'KPort'
		////	'{'
		////		('edges' '(' edges+=[KEdge|EString] ( "," edges+=[KEdge|EString])* ')' )?
		////		('data' '{' data+=KGraphData ( "," data+=KGraphData)* '}' )?
		////		('labels' '{' labels+=KLabel ( "," labels+=KLabel)* '}' )?
		////    '}';
		//	{KPort} "KPort" "{" ("edges" ":" edges+=[KEdge|EString] ("," edges+=[KEdge|EString])*)? ("data" ":" data+=KGraphData
		//	("," data+=KGraphData)*)? ("labels" ":" labels+=KLabel ("," labels+=KLabel)*)? "}";
		public ParserRule getRule() { return rule; }

		////	{KPort}
		////	'KPort'
		////	'{'
		////		('edges' '(' edges+=[KEdge|EString] ( "," edges+=[KEdge|EString])* ')' )?
		////		('data' '{' data+=KGraphData ( "," data+=KGraphData)* '}' )?
		////		('labels' '{' labels+=KLabel ( "," labels+=KLabel)* '}' )?
		////    '}';
		//{KPort} "KPort" "{" ("edges" ":" edges+=[KEdge|EString] ("," edges+=[KEdge|EString])*)? ("data" ":" data+=KGraphData
		//("," data+=KGraphData)*)? ("labels" ":" labels+=KLabel ("," labels+=KLabel)*)? "}"
		public Group getGroup() { return cGroup; }

		////	{KPort}
		////	'KPort'
		////	'{'
		////		('edges' '(' edges+=[KEdge|EString] ( "," edges+=[KEdge|EString])* ')' )?
		////		('data' '{' data+=KGraphData ( "," data+=KGraphData)* '}' )?
		////		('labels' '{' labels+=KLabel ( "," labels+=KLabel)* '}' )?
		////    '}';
		//{KPort}
		public Action getKPortAction_0() { return cKPortAction_0; }

		//"KPort"
		public Keyword getKPortKeyword_1() { return cKPortKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("edges" ":" edges+=[KEdge|EString] ("," edges+=[KEdge|EString])*)?
		public Group getGroup_3() { return cGroup_3; }

		//"edges"
		public Keyword getEdgesKeyword_3_0() { return cEdgesKeyword_3_0; }

		//":"
		public Keyword getColonKeyword_3_1() { return cColonKeyword_3_1; }

		//edges+=[KEdge|EString]
		public Assignment getEdgesAssignment_3_2() { return cEdgesAssignment_3_2; }

		//[KEdge|EString]
		public CrossReference getEdgesKEdgeCrossReference_3_2_0() { return cEdgesKEdgeCrossReference_3_2_0; }

		//EString
		public RuleCall getEdgesKEdgeEStringParserRuleCall_3_2_0_1() { return cEdgesKEdgeEStringParserRuleCall_3_2_0_1; }

		//("," edges+=[KEdge|EString])*
		public Group getGroup_3_3() { return cGroup_3_3; }

		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }

		//edges+=[KEdge|EString]
		public Assignment getEdgesAssignment_3_3_1() { return cEdgesAssignment_3_3_1; }

		//[KEdge|EString]
		public CrossReference getEdgesKEdgeCrossReference_3_3_1_0() { return cEdgesKEdgeCrossReference_3_3_1_0; }

		//EString
		public RuleCall getEdgesKEdgeEStringParserRuleCall_3_3_1_0_1() { return cEdgesKEdgeEStringParserRuleCall_3_3_1_0_1; }

		//("data" ":" data+=KGraphData ("," data+=KGraphData)*)?
		public Group getGroup_4() { return cGroup_4; }

		//"data"
		public Keyword getDataKeyword_4_0() { return cDataKeyword_4_0; }

		//":"
		public Keyword getColonKeyword_4_1() { return cColonKeyword_4_1; }

		//data+=KGraphData
		public Assignment getDataAssignment_4_2() { return cDataAssignment_4_2; }

		//KGraphData
		public RuleCall getDataKGraphDataParserRuleCall_4_2_0() { return cDataKGraphDataParserRuleCall_4_2_0; }

		//("," data+=KGraphData)*
		public Group getGroup_4_3() { return cGroup_4_3; }

		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }

		//data+=KGraphData
		public Assignment getDataAssignment_4_3_1() { return cDataAssignment_4_3_1; }

		//KGraphData
		public RuleCall getDataKGraphDataParserRuleCall_4_3_1_0() { return cDataKGraphDataParserRuleCall_4_3_1_0; }

		//("labels" ":" labels+=KLabel ("," labels+=KLabel)*)?
		public Group getGroup_5() { return cGroup_5; }

		//"labels"
		public Keyword getLabelsKeyword_5_0() { return cLabelsKeyword_5_0; }

		//":"
		public Keyword getColonKeyword_5_1() { return cColonKeyword_5_1; }

		//labels+=KLabel
		public Assignment getLabelsAssignment_5_2() { return cLabelsAssignment_5_2; }

		//KLabel
		public RuleCall getLabelsKLabelParserRuleCall_5_2_0() { return cLabelsKLabelParserRuleCall_5_2_0; }

		//("," labels+=KLabel)*
		public Group getGroup_5_3() { return cGroup_5_3; }

		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }

		//labels+=KLabel
		public Assignment getLabelsAssignment_5_3_1() { return cLabelsAssignment_5_3_1; }

		//KLabel
		public RuleCall getLabelsKLabelParserRuleCall_5_3_1_0() { return cLabelsKLabelParserRuleCall_5_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class KEdgeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "KEdge");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusHyphenMinusGreaterThanSignKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTargetKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTargetAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cTargetKNodeCrossReference_2_0 = (CrossReference)cTargetAssignment_2.eContents().get(0);
		private final RuleCall cTargetKNodeEStringParserRuleCall_2_0_1 = (RuleCall)cTargetKNodeCrossReference_2_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cSourcePortKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cSourcePortAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cSourcePortKPortCrossReference_4_1_0 = (CrossReference)cSourcePortAssignment_4_1.eContents().get(0);
		private final RuleCall cSourcePortKPortEStringParserRuleCall_4_1_0_1 = (RuleCall)cSourcePortKPortCrossReference_4_1_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTargetPortKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTargetPortAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cTargetPortKPortCrossReference_5_1_0 = (CrossReference)cTargetPortAssignment_5_1.eContents().get(0);
		private final RuleCall cTargetPortKPortEStringParserRuleCall_5_1_0_1 = (RuleCall)cTargetPortKPortCrossReference_5_1_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cDataKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cColonKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cDataAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cDataKGraphDataParserRuleCall_6_2_0 = (RuleCall)cDataAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cDataAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cDataKGraphDataParserRuleCall_6_3_1_0 = (RuleCall)cDataAssignment_6_3_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cLabelsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cColonKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cLabelsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cLabelsKLabelParserRuleCall_7_2_0 = (RuleCall)cLabelsAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cLabelsAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cLabelsKLabelParserRuleCall_7_3_1_0 = (RuleCall)cLabelsAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//KEdge: //	'KEdge'
		////	'{'
		////		'target' target=[KNode|EString]
		////		('sourcePort' sourcePort=[KPort|EString])?
		////		('targetPort' targetPort=[KPort|EString])?
		////		('data' '{' data+=KGraphData ( "," data+=KGraphData)* '}' )?
		////		('labels' '{' labels+=KLabel ( "," labels+=KLabel)* '}' )?
		////    '}';
		//	"-->" "target" target=[KNode|EString] "{" ("sourcePort" sourcePort=[KPort|EString])? ("targetPort"
		//	targetPort=[KPort|EString])? ("data" ":" data+=KGraphData ("," data+=KGraphData)*)? ("labels" ":" labels+=KLabel (","
		//	labels+=KLabel)*)? "}";
		public ParserRule getRule() { return rule; }

		////	'KEdge'
		////	'{'
		////		'target' target=[KNode|EString]
		////		('sourcePort' sourcePort=[KPort|EString])?
		////		('targetPort' targetPort=[KPort|EString])?
		////		('data' '{' data+=KGraphData ( "," data+=KGraphData)* '}' )?
		////		('labels' '{' labels+=KLabel ( "," labels+=KLabel)* '}' )?
		////    '}';
		//"-->" "target" target=[KNode|EString] "{" ("sourcePort" sourcePort=[KPort|EString])? ("targetPort"
		//targetPort=[KPort|EString])? ("data" ":" data+=KGraphData ("," data+=KGraphData)*)? ("labels" ":" labels+=KLabel (","
		//labels+=KLabel)*)? "}"
		public Group getGroup() { return cGroup; }

		////	'KEdge'
		////	'{'
		////		'target' target=[KNode|EString]
		////		('sourcePort' sourcePort=[KPort|EString])?
		////		('targetPort' targetPort=[KPort|EString])?
		////		('data' '{' data+=KGraphData ( "," data+=KGraphData)* '}' )?
		////		('labels' '{' labels+=KLabel ( "," labels+=KLabel)* '}' )?
		////    '}';
		//"-->"
		public Keyword getHyphenMinusHyphenMinusGreaterThanSignKeyword_0() { return cHyphenMinusHyphenMinusGreaterThanSignKeyword_0; }

		//"target"
		public Keyword getTargetKeyword_1() { return cTargetKeyword_1; }

		//target=[KNode|EString]
		public Assignment getTargetAssignment_2() { return cTargetAssignment_2; }

		//[KNode|EString]
		public CrossReference getTargetKNodeCrossReference_2_0() { return cTargetKNodeCrossReference_2_0; }

		//EString
		public RuleCall getTargetKNodeEStringParserRuleCall_2_0_1() { return cTargetKNodeEStringParserRuleCall_2_0_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("sourcePort" sourcePort=[KPort|EString])?
		public Group getGroup_4() { return cGroup_4; }

		//"sourcePort"
		public Keyword getSourcePortKeyword_4_0() { return cSourcePortKeyword_4_0; }

		//sourcePort=[KPort|EString]
		public Assignment getSourcePortAssignment_4_1() { return cSourcePortAssignment_4_1; }

		//[KPort|EString]
		public CrossReference getSourcePortKPortCrossReference_4_1_0() { return cSourcePortKPortCrossReference_4_1_0; }

		//EString
		public RuleCall getSourcePortKPortEStringParserRuleCall_4_1_0_1() { return cSourcePortKPortEStringParserRuleCall_4_1_0_1; }

		//("targetPort" targetPort=[KPort|EString])?
		public Group getGroup_5() { return cGroup_5; }

		//"targetPort"
		public Keyword getTargetPortKeyword_5_0() { return cTargetPortKeyword_5_0; }

		//targetPort=[KPort|EString]
		public Assignment getTargetPortAssignment_5_1() { return cTargetPortAssignment_5_1; }

		//[KPort|EString]
		public CrossReference getTargetPortKPortCrossReference_5_1_0() { return cTargetPortKPortCrossReference_5_1_0; }

		//EString
		public RuleCall getTargetPortKPortEStringParserRuleCall_5_1_0_1() { return cTargetPortKPortEStringParserRuleCall_5_1_0_1; }

		//("data" ":" data+=KGraphData ("," data+=KGraphData)*)?
		public Group getGroup_6() { return cGroup_6; }

		//"data"
		public Keyword getDataKeyword_6_0() { return cDataKeyword_6_0; }

		//":"
		public Keyword getColonKeyword_6_1() { return cColonKeyword_6_1; }

		//data+=KGraphData
		public Assignment getDataAssignment_6_2() { return cDataAssignment_6_2; }

		//KGraphData
		public RuleCall getDataKGraphDataParserRuleCall_6_2_0() { return cDataKGraphDataParserRuleCall_6_2_0; }

		//("," data+=KGraphData)*
		public Group getGroup_6_3() { return cGroup_6_3; }

		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }

		//data+=KGraphData
		public Assignment getDataAssignment_6_3_1() { return cDataAssignment_6_3_1; }

		//KGraphData
		public RuleCall getDataKGraphDataParserRuleCall_6_3_1_0() { return cDataKGraphDataParserRuleCall_6_3_1_0; }

		//("labels" ":" labels+=KLabel ("," labels+=KLabel)*)?
		public Group getGroup_7() { return cGroup_7; }

		//"labels"
		public Keyword getLabelsKeyword_7_0() { return cLabelsKeyword_7_0; }

		//":"
		public Keyword getColonKeyword_7_1() { return cColonKeyword_7_1; }

		//labels+=KLabel
		public Assignment getLabelsAssignment_7_2() { return cLabelsAssignment_7_2; }

		//KLabel
		public RuleCall getLabelsKLabelParserRuleCall_7_2_0() { return cLabelsKLabelParserRuleCall_7_2_0; }

		//("," labels+=KLabel)*
		public Group getGroup_7_3() { return cGroup_7_3; }

		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }

		//labels+=KLabel
		public Assignment getLabelsAssignment_7_3_1() { return cLabelsAssignment_7_3_1; }

		//KLabel
		public RuleCall getLabelsKLabelParserRuleCall_7_3_1_0() { return cLabelsKLabelParserRuleCall_7_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class KGraphDataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "KGraphData");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cKRenderingParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cKShapeLayoutParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cKEdgeLayoutParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//// Error marker is a false positive; generation works anyway!
		////  It occurs if eSuperType references in krendering.ecore/klayoutdata.ecore
		////  are like ../../de.cau.cs.kieler.core.kgraph/model/kgraph.ecore#//KGraphData
		////  but should be platform:/resource/de.cau.cs.kieler.core.kgraph/model/kgraph.ecore#//KGraphData
		////  since Xtext obviously compares concrete string representations of the fragmentURIs.
		////  This is why packages are referred to the same way in the preamble.   
		////PersistentEntry returns PersistentEntry:
		////	'PersistentEntry'
		////	'{'
		////		'key' key=EString
		////		('value' value=EString)?
		////    '}';
		////EString returns ecore::EString:
		////	STRING | ID;
		//KGraphData: //	{KGraphData}
		////	'KGraphData'
		////	'{'
		////		('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
		////    '}';
		//	KRendering | KShapeLayout | KEdgeLayout;
		public ParserRule getRule() { return rule; }

		////	{KGraphData}
		////	'KGraphData'
		////	'{'
		////		('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
		////    '}';
		//KRendering //PersistentEntry returns PersistentEntry:
		////	'PersistentEntry'
		////	'{'
		////		'key' key=EString
		////		('value' value=EString)?
		////    '}';
		////EString returns ecore::EString:
		////	STRING | ID;
		//| KShapeLayout | KEdgeLayout
		public Alternatives getAlternatives() { return cAlternatives; }

		////	{KGraphData}
		////	'KGraphData'
		////	'{'
		////		('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
		////    '}';
		//KRendering
		public RuleCall getKRenderingParserRuleCall_0() { return cKRenderingParserRuleCall_0; }

		//KShapeLayout
		public RuleCall getKShapeLayoutParserRuleCall_1() { return cKShapeLayoutParserRuleCall_1; }

		////PersistentEntry returns PersistentEntry:
		////	'PersistentEntry'
		////	'{'
		////		'key' key=EString
		////		('value' value=EString)?
		////    '}';
		////EString returns ecore::EString:
		////	STRING | ID;
		//KEdgeLayout
		public RuleCall getKEdgeLayoutParserRuleCall_2() { return cKEdgeLayoutParserRuleCall_2; }
	}
	
	
	private KNodeElements pKNode;
	private KLabelElements pKLabel;
	private KPortElements pKPort;
	private KEdgeElements pKEdge;
	private KGraphDataElements pKGraphData;
	
	private final GrammarProvider grammarProvider;

	private KRenderingGrammarAccess gaKRendering;

	@Inject
	public KGraphGrammarAccess(GrammarProvider grammarProvider,
		KRenderingGrammarAccess gaKRendering) {
		this.grammarProvider = grammarProvider;
		this.gaKRendering = gaKRendering;
	}
	
	public Grammar getGrammar() {	
		return grammarProvider.getGrammar(this);
	}
	

	public KRenderingGrammarAccess getKRenderingGrammarAccess() {
		return gaKRendering;
	}

	
	//KNode: //	{KNode}
	////	'KNode'
	////	'{'
	////		('incomingEdges' '(' incomingEdges+=[KEdge|EString] ( "," incomingEdges+=[KEdge|EString])* ')' )?
	////		('data' '{' data+=KGraphData ( "," data+=KGraphData)* '}' )?
	////		('labels' '{' labels+=KLabel ( "," labels+=KLabel)* '}' )?
	////		('children' '{' children+=KNode ( "," children+=KNode)* '}' )?
	////		('ports' '{' ports+=KPort ( "," ports+=KPort)* '}' )?
	////		('outgoingEdges' '{' outgoingEdges+=KEdge ( "," outgoingEdges+=KEdge)* '}' )?
	////    '}';
	//	{KNode} "KNode" "{" ("ports" ports+=KPort ("," ports+=KPort)*)? ("data" ":" data+=KGraphData ("," data+=KGraphData)*)? //('labels' '{' labels+=KLabel ( "," labels+=KLabel)* '}' )?
	//	("children" ":" children+=KNode ("," children+=KNode)*)? "}" (outgoingEdges+=KEdge ("," outgoingEdges+=KEdge)*)?;
	public KNodeElements getKNodeAccess() {
		return (pKNode != null) ? pKNode : (pKNode = new KNodeElements());
	}
	
	public ParserRule getKNodeRule() {
		return getKNodeAccess().getRule();
	}

	//KLabel: //	'KLabel'
	////	'{'
	////		'text' text=EString
	////		('data' '{' data+=KGraphData ( "," data+=KGraphData)* '}' )?
	////    '}';
	//	"KLabel" text=EString "{" ("data" ":" data+=KGraphData ("," data+=KGraphData)*)? "}";
	public KLabelElements getKLabelAccess() {
		return (pKLabel != null) ? pKLabel : (pKLabel = new KLabelElements());
	}
	
	public ParserRule getKLabelRule() {
		return getKLabelAccess().getRule();
	}

	//KPort: //	{KPort}
	////	'KPort'
	////	'{'
	////		('edges' '(' edges+=[KEdge|EString] ( "," edges+=[KEdge|EString])* ')' )?
	////		('data' '{' data+=KGraphData ( "," data+=KGraphData)* '}' )?
	////		('labels' '{' labels+=KLabel ( "," labels+=KLabel)* '}' )?
	////    '}';
	//	{KPort} "KPort" "{" ("edges" ":" edges+=[KEdge|EString] ("," edges+=[KEdge|EString])*)? ("data" ":" data+=KGraphData
	//	("," data+=KGraphData)*)? ("labels" ":" labels+=KLabel ("," labels+=KLabel)*)? "}";
	public KPortElements getKPortAccess() {
		return (pKPort != null) ? pKPort : (pKPort = new KPortElements());
	}
	
	public ParserRule getKPortRule() {
		return getKPortAccess().getRule();
	}

	//KEdge: //	'KEdge'
	////	'{'
	////		'target' target=[KNode|EString]
	////		('sourcePort' sourcePort=[KPort|EString])?
	////		('targetPort' targetPort=[KPort|EString])?
	////		('data' '{' data+=KGraphData ( "," data+=KGraphData)* '}' )?
	////		('labels' '{' labels+=KLabel ( "," labels+=KLabel)* '}' )?
	////    '}';
	//	"-->" "target" target=[KNode|EString] "{" ("sourcePort" sourcePort=[KPort|EString])? ("targetPort"
	//	targetPort=[KPort|EString])? ("data" ":" data+=KGraphData ("," data+=KGraphData)*)? ("labels" ":" labels+=KLabel (","
	//	labels+=KLabel)*)? "}";
	public KEdgeElements getKEdgeAccess() {
		return (pKEdge != null) ? pKEdge : (pKEdge = new KEdgeElements());
	}
	
	public ParserRule getKEdgeRule() {
		return getKEdgeAccess().getRule();
	}

	//// Error marker is a false positive; generation works anyway!
	////  It occurs if eSuperType references in krendering.ecore/klayoutdata.ecore
	////  are like ../../de.cau.cs.kieler.core.kgraph/model/kgraph.ecore#//KGraphData
	////  but should be platform:/resource/de.cau.cs.kieler.core.kgraph/model/kgraph.ecore#//KGraphData
	////  since Xtext obviously compares concrete string representations of the fragmentURIs.
	////  This is why packages are referred to the same way in the preamble.   
	////PersistentEntry returns PersistentEntry:
	////	'PersistentEntry'
	////	'{'
	////		'key' key=EString
	////		('value' value=EString)?
	////    '}';
	////EString returns ecore::EString:
	////	STRING | ID;
	//KGraphData: //	{KGraphData}
	////	'KGraphData'
	////	'{'
	////		('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	////    '}';
	//	KRendering | KShapeLayout | KEdgeLayout;
	public KGraphDataElements getKGraphDataAccess() {
		return (pKGraphData != null) ? pKGraphData : (pKGraphData = new KGraphDataElements());
	}
	
	public ParserRule getKGraphDataRule() {
		return getKGraphDataAccess().getRule();
	}

	//KRenderingLibrary: //	{KRenderingLibrary}
	////	'KRenderingLibrary'
	////	'{'
	////		('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	////		('renderings' '{' renderings+=KRendering ( "," renderings+=KRendering)* '}' )?
	////    '}';
	//	{KRenderingLibrary} "KRenderingLibrary" "{" (renderings+=KRendering ("," renderings+=KRendering)*)? "}";
	public KRenderingGrammarAccess.KRenderingLibraryElements getKRenderingLibraryAccess() {
		return gaKRendering.getKRenderingLibraryAccess();
	}
	
	public ParserRule getKRenderingLibraryRule() {
		return getKRenderingLibraryAccess().getRule();
	}

	//KRendering:
	//	KEllipse | KRectangle | KRoundedRectangle | KPolyline_Impl | KPolygon | KImage | KArc | KRenderingRef | KChildArea |
	//	KText | KCustomRendering | KSpline;
	public KRenderingGrammarAccess.KRenderingElements getKRenderingAccess() {
		return gaKRendering.getKRenderingAccess();
	}
	
	public ParserRule getKRenderingRule() {
		return getKRenderingAccess().getRule();
	}

	//KPlacementData:
	//	KDecoratorPlacementData | KGridPlacementData | KStackPlacementData | KDirectPlacementData | KPolylinePlacementData;
	public KRenderingGrammarAccess.KPlacementDataElements getKPlacementDataAccess() {
		return gaKRendering.getKPlacementDataAccess();
	}
	
	public ParserRule getKPlacementDataRule() {
		return getKPlacementDataAccess().getRule();
	}

	//// | KStyle_Impl;
	//KStyle:
	//	KForegroundColor | KBackgroundColor | KLineWidth | KVisibility | KLineStyle | KVerticalAlignment |
	//	KHorizontalAlignment;
	public KRenderingGrammarAccess.KStyleElements getKStyleAccess() {
		return gaKRendering.getKStyleAccess();
	}
	
	public ParserRule getKStyleRule() {
		return getKStyleAccess().getRule();
	}

	//KPlacement:
	//	KGridPlacement | KStackPlacement;
	public KRenderingGrammarAccess.KPlacementElements getKPlacementAccess() {
		return gaKRendering.getKPlacementAccess();
	}
	
	public ParserRule getKPlacementRule() {
		return getKPlacementAccess().getRule();
	}

	//KXPosition:
	//	KLeftPosition | KRightPosition;
	public KRenderingGrammarAccess.KXPositionElements getKXPositionAccess() {
		return gaKRendering.getKXPositionAccess();
	}
	
	public ParserRule getKXPositionRule() {
		return getKXPositionAccess().getRule();
	}

	//KYPosition:
	//	KTopPosition | KBottomPosition;
	public KRenderingGrammarAccess.KYPositionElements getKYPositionAccess() {
		return gaKRendering.getKYPositionAccess();
	}
	
	public ParserRule getKYPositionRule() {
		return getKYPositionAccess().getRule();
	}

	//KRenderingRef:
	//	"KRenderingRef" "{" ("references" "(" references+=[KRenderingRef|EString] ("," references+=[KRenderingRef|EString])*
	//	")")? "rendering" rendering=[KRendering|EString] // ('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	//	("placementData" placementData=KPlacementData)? ("styles" "{" styles+=KStyle ("," styles+=KStyle)* "}")? "}";
	public KRenderingGrammarAccess.KRenderingRefElements getKRenderingRefAccess() {
		return gaKRendering.getKRenderingRefAccess();
	}
	
	public ParserRule getKRenderingRefRule() {
		return getKRenderingRefAccess().getRule();
	}

	////KStyle_Impl returns KStyle:
	////	propagateToChildren?='propagateToChildren'
	////	'KStyle'
	////;
	//KEllipse: //	{KEllipse}
	////	'KEllipse'
	////	'{'
	////		('references' '(' references+=[KRenderingRef|EString] ( "," references+=[KRenderingRef|EString])* ')' )?
	////		('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	////		('placementData' placementData=KPlacementData)?
	////		('styles' '{' styles+=KStyle ( "," styles+=KStyle)* '}' )?
	////		('children' '{' children+=KRendering ( "," children+=KRendering)* '}' )?
	////		('childPlacement' childPlacement=KPlacement)?
	////    '}';
	//	{KEllipse} "KEllipse" "{" ("styles" ":" styles+=KStyle ("," styles+=KStyle)*)? ("placementData" ":"
	//	placementData=KPlacementData)? ("childPlacement" ":" childPlacement=KPlacement)? ("children" ":" children+=KRendering
	//	("," children+=KRendering)*)? "}";
	public KRenderingGrammarAccess.KEllipseElements getKEllipseAccess() {
		return gaKRendering.getKEllipseAccess();
	}
	
	public ParserRule getKEllipseRule() {
		return getKEllipseAccess().getRule();
	}

	//KRectangle: //	{KRectangle}
	////	'KRectangle'
	////	'{'
	////		('references' '(' references+=[KRenderingRef|EString] ( "," references+=[KRenderingRef|EString])* ')' )?
	////		('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	////		('placementData' ':' placementData=KPlacementData)?
	////		('styles' '{' styles+=KStyle ( "," styles+=KStyle)* '}' )?
	////		('children' '{' children+=KRendering ( "," children+=KRendering)* '}' )?
	////		('childPlacement' childPlacement=KPlacement)?
	////    '}';
	//	{KRectangle} "KRectangle" "{" ("styles" ":" styles+=KStyle ("," styles+=KStyle)*)? ("placementData" ":"
	//	placementData=KPlacementData)? ("childPlacement" ":" childPlacement=KPlacement)? ("children" ":" children+=KRendering
	//	("," children+=KRendering)*)? "}";
	public KRenderingGrammarAccess.KRectangleElements getKRectangleAccess() {
		return gaKRendering.getKRectangleAccess();
	}
	
	public ParserRule getKRectangleRule() {
		return getKRectangleAccess().getRule();
	}

	//KRoundedRectangle: //	'KRoundedRectangle'
	////	'{'
	////		'cornerWidth' cornerWidth=EFloat
	////		'cornerHeight' cornerHeight=EFloat
	////		('references' '(' references+=[KRenderingRef|EString] ( "," references+=[KRenderingRef|EString])* ')' )?
	////		('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	////		('placementData' placementData=KPlacementData)?
	////		('styles' '{' styles+=KStyle ( "," styles+=KStyle)* '}' )?
	////		('children' '{' children+=KRendering ( "," children+=KRendering)* '}' )?
	////		('childPlacement' childPlacement=KPlacement)?
	////    '}';
	//	"KRoundedRectangle" "{" ("cornerWidth" cornerWidth=EFloat "cornerHeight" cornerHeight=EFloat | "cornerHeight"
	//	cornerHeight=EFloat "cornerWidth" cornerWidth=EFloat) ("styles" ":" styles+=KStyle ("," styles+=KStyle)*)?
	//	("placementData" ":" placementData=KPlacementData)? ("childPlacement" ":" childPlacement=KPlacement)? ("children" ":"
	//	children+=KRendering ("," children+=KRendering)*)? "}";
	public KRenderingGrammarAccess.KRoundedRectangleElements getKRoundedRectangleAccess() {
		return gaKRendering.getKRoundedRectangleAccess();
	}
	
	public ParserRule getKRoundedRectangleRule() {
		return getKRoundedRectangleAccess().getRule();
	}

	//KPolyline_Impl returns KPolyline: //	{KPolyline}
	////	'KPolyline'
	////	'{'
	////		('references' '(' references+=[KRenderingRef|EString] ( "," references+=[KRenderingRef|EString])* ')' )?
	////		('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	////		('placementData' placementData=KPlacementData)?
	////		('styles' '{' styles+=KStyle ( "," styles+=KStyle)* '}' )?
	////		('children' '{' children+=KRendering ( "," children+=KRendering)* '}' )?
	////		('childPlacement' childPlacement=KPlacement)?
	////    '}';
	//	{KPolyline} "KPolyline" "{" ("styles" ":" styles+=KStyle ("," styles+=KStyle)*)? ("placementData" ":"
	//	placementData=KPlacementData)? ("childPlacement" ":" childPlacement=KPlacement)? ("children" ":" children+=KRendering
	//	("," children+=KRendering)*)? "}";
	public KRenderingGrammarAccess.KPolyline_ImplElements getKPolyline_ImplAccess() {
		return gaKRendering.getKPolyline_ImplAccess();
	}
	
	public ParserRule getKPolyline_ImplRule() {
		return getKPolyline_ImplAccess().getRule();
	}

	//KPolygon: //	{KPolygon}
	////	'KPolygon'
	////	'{'
	////		('references' '(' references+=[KRenderingRef|EString] ( "," references+=[KRenderingRef|EString])* ')' )?
	////		('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	////		('placementData' placementData=KPlacementData)?
	////		('styles' '{' styles+=KStyle ( "," styles+=KStyle)* '}' )?
	////		('children' '{' children+=KRendering ( "," children+=KRendering)* '}' )?
	////		('childPlacement' childPlacement=KPlacement)?
	////    '}';
	//	{KPolygon} "KPolygon" "{" ("styles" ":" styles+=KStyle ("," styles+=KStyle)*)? ("placementData" ":"
	//	placementData=KPlacementData)? ("childPlacement" ":" childPlacement=KPlacement)? ("children" ":" children+=KRendering
	//	("," children+=KRendering)*)? "}";
	public KRenderingGrammarAccess.KPolygonElements getKPolygonAccess() {
		return gaKRendering.getKPolygonAccess();
	}
	
	public ParserRule getKPolygonRule() {
		return getKPolygonAccess().getRule();
	}

	//KImage:
	//	"KImage" "{" "bundleName" bundleName=EString "imagePath" imagePath=EString ("references" "("
	//	references+=[KRenderingRef|EString] ("," references+=[KRenderingRef|EString])* ")")? // ('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	//	("placementData" placementData=KPlacementData)? ("styles" "{" styles+=KStyle ("," styles+=KStyle)* "}")? ("children"
	//	"{" children+=KRendering ("," children+=KRendering)* "}")? ("childPlacement" childPlacement=KPlacement)? "}";
	public KRenderingGrammarAccess.KImageElements getKImageAccess() {
		return gaKRendering.getKImageAccess();
	}
	
	public ParserRule getKImageRule() {
		return getKImageAccess().getRule();
	}

	//KArc:
	//	{KArc} "KArc" "{" ("startAngle" startAngle=EFloat)? ("arcAngle" arcAngle=EFloat)? ("references" "("
	//	references+=[KRenderingRef|EString] ("," references+=[KRenderingRef|EString])* ")")? // ('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	//	("placementData" placementData=KPlacementData)? ("styles" "{" styles+=KStyle ("," styles+=KStyle)* "}")? ("children"
	//	"{" children+=KRendering ("," children+=KRendering)* "}")? ("childPlacement" childPlacement=KPlacement)? "}";
	public KRenderingGrammarAccess.KArcElements getKArcAccess() {
		return gaKRendering.getKArcAccess();
	}
	
	public ParserRule getKArcRule() {
		return getKArcAccess().getRule();
	}

	//KChildArea:
	//	{KChildArea} "KChildArea" "{" ("references" "(" references+=[KRenderingRef|EString] (","
	//	references+=[KRenderingRef|EString])* ")")? // ('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	//	("placementData" placementData=KPlacementData)? ("styles" "{" styles+=KStyle ("," styles+=KStyle)* "}")? "}";
	public KRenderingGrammarAccess.KChildAreaElements getKChildAreaAccess() {
		return gaKRendering.getKChildAreaAccess();
	}
	
	public ParserRule getKChildAreaRule() {
		return getKChildAreaAccess().getRule();
	}

	//KText:
	//	"KText" "{" clip?="clip" ("text" text=EString)? ("references" "(" references+=[KRenderingRef|EString] (","
	//	references+=[KRenderingRef|EString])* ")")? // ('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	//	("placementData" placementData=KPlacementData)? ("styles" "{" styles+=KStyle ("," styles+=KStyle)* "}")? ("children"
	//	"{" children+=KRendering ("," children+=KRendering)* "}")? ("childPlacement" childPlacement=KPlacement)? "}";
	public KRenderingGrammarAccess.KTextElements getKTextAccess() {
		return gaKRendering.getKTextAccess();
	}
	
	public ParserRule getKTextRule() {
		return getKTextAccess().getRule();
	}

	//KCustomRendering:
	//	"KCustomRendering" "{" "className" className=EString "bundleName" bundleName=EString ("references" "("
	//	references+=[KRenderingRef|EString] ("," references+=[KRenderingRef|EString])* ")")? // ('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	//	("placementData" placementData=KPlacementData)? ("styles" "{" styles+=KStyle ("," styles+=KStyle)* "}")? ("children"
	//	"{" children+=KRendering ("," children+=KRendering)* "}")? ("childPlacement" childPlacement=KPlacement)? "}";
	public KRenderingGrammarAccess.KCustomRenderingElements getKCustomRenderingAccess() {
		return gaKRendering.getKCustomRenderingAccess();
	}
	
	public ParserRule getKCustomRenderingRule() {
		return getKCustomRenderingAccess().getRule();
	}

	//KSpline:
	//	{KSpline} "KSpline" "{" ("references" "(" references+=[KRenderingRef|EString] (","
	//	references+=[KRenderingRef|EString])* ")")? // ('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	//	("placementData" placementData=KPlacementData)? ("styles" "{" styles+=KStyle ("," styles+=KStyle)* "}")? ("children"
	//	"{" children+=KRendering ("," children+=KRendering)* "}")? ("childPlacement" childPlacement=KPlacement)? "}";
	public KRenderingGrammarAccess.KSplineElements getKSplineAccess() {
		return gaKRendering.getKSplineAccess();
	}
	
	public ParserRule getKSplineRule() {
		return getKSplineAccess().getRule();
	}

	//KDecoratorPlacementData:
	//	"KDecoratorPlacementData" "{" relative?="relative" "location" location=EFloat ("xOffset" xOffset=EFloat)? ("yOffset"
	//	yOffset=EFloat)? ("width" width=EFloat)? ("height" height=EFloat)? "}";
	public KRenderingGrammarAccess.KDecoratorPlacementDataElements getKDecoratorPlacementDataAccess() {
		return gaKRendering.getKDecoratorPlacementDataAccess();
	}
	
	public ParserRule getKDecoratorPlacementDataRule() {
		return getKDecoratorPlacementDataAccess().getRule();
	}

	//KGridPlacementData:
	//	"KGridPlacementData" "{" "widthHint" widthHint=EFloat "heightHint" heightHint=EFloat "horizontalIndent"
	//	horizontalIndent=EFloat "verticalIndent" verticalIndent=EFloat "}";
	public KRenderingGrammarAccess.KGridPlacementDataElements getKGridPlacementDataAccess() {
		return gaKRendering.getKGridPlacementDataAccess();
	}
	
	public ParserRule getKGridPlacementDataRule() {
		return getKGridPlacementDataAccess().getRule();
	}

	//KStackPlacementData:
	//	"KStackPlacementData" "{" "insetRight" insetRight=EFloat "insetBottom" insetBottom=EFloat "insetLeft" insetLeft=EFloat
	//	"insetTop" insetTop=EFloat "}";
	public KRenderingGrammarAccess.KStackPlacementDataElements getKStackPlacementDataAccess() {
		return gaKRendering.getKStackPlacementDataAccess();
	}
	
	public ParserRule getKStackPlacementDataRule() {
		return getKStackPlacementDataAccess().getRule();
	}

	//KDirectPlacementData:
	//	"KDirectPlacementData" "{" "topLeft" topLeft=KPosition "bottomRight" bottomRight=KPosition "}";
	public KRenderingGrammarAccess.KDirectPlacementDataElements getKDirectPlacementDataAccess() {
		return gaKRendering.getKDirectPlacementDataAccess();
	}
	
	public ParserRule getKDirectPlacementDataRule() {
		return getKDirectPlacementDataAccess().getRule();
	}

	//KPolylinePlacementData: //	'KPolylinePlacementData'
	////	'{'
	////		'points' '{' points+=KPosition ( "," points+=KPosition)* '}' 
	////    '}';
	//	"points" ":" points+=KPosition ("," points+=KPosition)*;
	public KRenderingGrammarAccess.KPolylinePlacementDataElements getKPolylinePlacementDataAccess() {
		return gaKRendering.getKPolylinePlacementDataAccess();
	}
	
	public ParserRule getKPolylinePlacementDataRule() {
		return getKPolylinePlacementDataAccess().getRule();
	}

	//EFloat returns ecore::EFloat:
	//	"-"? INT? "." INT (("E" | "e") "-"? INT)?;
	public KRenderingGrammarAccess.EFloatElements getEFloatAccess() {
		return gaKRendering.getEFloatAccess();
	}
	
	public ParserRule getEFloatRule() {
		return getEFloatAccess().getRule();
	}

	//EBoolean returns ecore::EBoolean:
	//	"true" | "false";
	public KRenderingGrammarAccess.EBooleanElements getEBooleanAccess() {
		return gaKRendering.getEBooleanAccess();
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}

	//KPosition:
	//	"KPosition" "{" "x" x=KXPosition "y" y=KYPosition "}";
	public KRenderingGrammarAccess.KPositionElements getKPositionAccess() {
		return gaKRendering.getKPositionAccess();
	}
	
	public ParserRule getKPositionRule() {
		return getKPositionAccess().getRule();
	}

	//KLeftPosition:
	//	{KLeftPosition} "KLeftPosition" "{" ("absolute" absolute=EFloat)? ("relative" relative=EFloat)? "}";
	public KRenderingGrammarAccess.KLeftPositionElements getKLeftPositionAccess() {
		return gaKRendering.getKLeftPositionAccess();
	}
	
	public ParserRule getKLeftPositionRule() {
		return getKLeftPositionAccess().getRule();
	}

	//KRightPosition:
	//	{KRightPosition} "KRightPosition" "{" ("absolute" absolute=EFloat)? ("relative" relative=EFloat)? "}";
	public KRenderingGrammarAccess.KRightPositionElements getKRightPositionAccess() {
		return gaKRendering.getKRightPositionAccess();
	}
	
	public ParserRule getKRightPositionRule() {
		return getKRightPositionAccess().getRule();
	}

	//KTopPosition:
	//	{KTopPosition} "KTopPosition" "{" ("absolute" absolute=EFloat)? ("relative" relative=EFloat)? "}";
	public KRenderingGrammarAccess.KTopPositionElements getKTopPositionAccess() {
		return gaKRendering.getKTopPositionAccess();
	}
	
	public ParserRule getKTopPositionRule() {
		return getKTopPositionAccess().getRule();
	}

	//KBottomPosition:
	//	{KBottomPosition} "KBottomPosition" "{" ("absolute" absolute=EFloat)? ("relative" relative=EFloat)? "}";
	public KRenderingGrammarAccess.KBottomPositionElements getKBottomPositionAccess() {
		return gaKRendering.getKBottomPositionAccess();
	}
	
	public ParserRule getKBottomPositionRule() {
		return getKBottomPositionAccess().getRule();
	}

	//KForegroundColor: //	propagateToChildren?='propagateToChildren'
	////	'KForegroundColor'
	////	'{'
	////		'red' red=EInt
	////		'green' green=EInt
	////		'blue' blue=EInt
	////    '}';
	//	{KForegroundColor} "KForegroundColor" "{" propagateToChildren?="propagateToChildren"? ("red" red=EInt)? ("green"
	//	green=EInt)? ("blue" blue=EInt)? "}";
	public KRenderingGrammarAccess.KForegroundColorElements getKForegroundColorAccess() {
		return gaKRendering.getKForegroundColorAccess();
	}
	
	public ParserRule getKForegroundColorRule() {
		return getKForegroundColorAccess().getRule();
	}

	//KBackgroundColor: //	propagateToChildren?='propagateToChildren'
	////	'KBackgroundColor'
	////	'{'
	////		'red' red=EInt
	////		'green' green=EInt
	////		'blue' blue=EInt
	////    '}';
	//	{KBackgroundColor} "KBackgroundColor" "{" propagateToChildren?="propagateToChildren"? ("red" red=EInt)? ("green"
	//	green=EInt)? ("blue" blue=EInt)? "}";
	public KRenderingGrammarAccess.KBackgroundColorElements getKBackgroundColorAccess() {
		return gaKRendering.getKBackgroundColorAccess();
	}
	
	public ParserRule getKBackgroundColorRule() {
		return getKBackgroundColorAccess().getRule();
	}

	//KLineWidth: //	propagateToChildren?='propagateToChildren'
	////	'KLineWidth'
	////	'{'
	////		'lineWidth' lineWidth=EInt
	////    '}';
	//	"KLineWidth" lineWidth=EInt propagateToChildren?="propagateToChildren"?;
	public KRenderingGrammarAccess.KLineWidthElements getKLineWidthAccess() {
		return gaKRendering.getKLineWidthAccess();
	}
	
	public ParserRule getKLineWidthRule() {
		return getKLineWidthAccess().getRule();
	}

	//KVisibility:
	//	KForegroundVisibility | KBackgroundVisibility;
	public KRenderingGrammarAccess.KVisibilityElements getKVisibilityAccess() {
		return gaKRendering.getKVisibilityAccess();
	}
	
	public ParserRule getKVisibilityRule() {
		return getKVisibilityAccess().getRule();
	}

	//KForegroundVisibility:
	//	{KForegroundVisibility} "KForegroundVisibility" visible?="visible"? propagateToChildren?="propagateToChildren"?;
	public KRenderingGrammarAccess.KForegroundVisibilityElements getKForegroundVisibilityAccess() {
		return gaKRendering.getKForegroundVisibilityAccess();
	}
	
	public ParserRule getKForegroundVisibilityRule() {
		return getKForegroundVisibilityAccess().getRule();
	}

	//KBackgroundVisibility:
	//	{KBackgroundVisibility} "KBackgroundVisibility" visible?="visible"? propagateToChildren?="propagateToChildren"?;
	public KRenderingGrammarAccess.KBackgroundVisibilityElements getKBackgroundVisibilityAccess() {
		return gaKRendering.getKBackgroundVisibilityAccess();
	}
	
	public ParserRule getKBackgroundVisibilityRule() {
		return getKBackgroundVisibilityAccess().getRule();
	}

	//KLineStyle: //	propagateToChildren?='propagateToChildren'
	////	'KLineStyle'
	////	'{'
	////		'lineStyle' lineStyle=LineStyle
	////    '}';
	//	{KLineStyle} "KLineStyle" lineStyle=LineStyle? propagateToChildren?="propagateToChildren"?;
	public KRenderingGrammarAccess.KLineStyleElements getKLineStyleAccess() {
		return gaKRendering.getKLineStyleAccess();
	}
	
	public ParserRule getKLineStyleRule() {
		return getKLineStyleAccess().getRule();
	}

	//KVerticalAlignment: //	propagateToChildren?='propagateToChildren'
	////	'KVerticalAlignment'
	////	'{'
	////		'verticalAlignment' verticalAlignment=VerticalAlignment
	////    '}';
	//	"KVerticalAlignment" verticalAlignment=VerticalAlignment propagateToChildren?="propagateToChildren"?;
	public KRenderingGrammarAccess.KVerticalAlignmentElements getKVerticalAlignmentAccess() {
		return gaKRendering.getKVerticalAlignmentAccess();
	}
	
	public ParserRule getKVerticalAlignmentRule() {
		return getKVerticalAlignmentAccess().getRule();
	}

	//KHorizontalAlignment: //	propagateToChildren?='propagateToChildren'
	////	'KHorizontalAlignment'
	////	'{'
	////		'horizontalAlignment' horizontalAlignment=HorizontalAlignment
	////    '}';
	//	"KHorizontalAlignment" horizontalAlignment=HorizontalAlignment propagateToChildren?="propagateToChildren";
	public KRenderingGrammarAccess.KHorizontalAlignmentElements getKHorizontalAlignmentAccess() {
		return gaKRendering.getKHorizontalAlignmentAccess();
	}
	
	public ParserRule getKHorizontalAlignmentRule() {
		return getKHorizontalAlignmentAccess().getRule();
	}

	//KGridPlacement: //	'KGridPlacement'
	////	'{'
	////		'numColumns' numColumns=EInt
	////    '}';
	//	{KGridPlacement} "KGridPlacement" numColumns=EInt;
	public KRenderingGrammarAccess.KGridPlacementElements getKGridPlacementAccess() {
		return gaKRendering.getKGridPlacementAccess();
	}
	
	public ParserRule getKGridPlacementRule() {
		return getKGridPlacementAccess().getRule();
	}

	//KStackPlacement:
	//	{KStackPlacement} "KStackPlacement";
	public KRenderingGrammarAccess.KStackPlacementElements getKStackPlacementAccess() {
		return gaKRendering.getKStackPlacementAccess();
	}
	
	public ParserRule getKStackPlacementRule() {
		return getKStackPlacementAccess().getRule();
	}

	//enum LineStyle:
	//	SOLID | DASH | DOT | DASHDOT | DASHDOTDOT;
	public KRenderingGrammarAccess.LineStyleElements getLineStyleAccess() {
		return gaKRendering.getLineStyleAccess();
	}
	
	public EnumRule getLineStyleRule() {
		return getLineStyleAccess().getRule();
	}

	//enum VerticalAlignment:
	//	TOP | CENTER | BOTTOM;
	public KRenderingGrammarAccess.VerticalAlignmentElements getVerticalAlignmentAccess() {
		return gaKRendering.getVerticalAlignmentAccess();
	}
	
	public EnumRule getVerticalAlignmentRule() {
		return getVerticalAlignmentAccess().getRule();
	}

	//enum HorizontalAlignment:
	//	LEFT | CENTER | RIGHT;
	public KRenderingGrammarAccess.HorizontalAlignmentElements getHorizontalAlignmentAccess() {
		return gaKRendering.getHorizontalAlignmentAccess();
	}
	
	public EnumRule getHorizontalAlignmentRule() {
		return getHorizontalAlignmentAccess().getRule();
	}

	//EInt returns ecore::EInt:
	//	"-"? INT;
	public KRenderingGrammarAccess.EIntElements getEIntAccess() {
		return gaKRendering.getEIntAccess();
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}

	//KShapeLayout: //	{KShapeLayout}
	////	'KShapeLayout'
	////	'{'
	////		('xpos' xpos=EFloat)?
	////		('ypos' ypos=EFloat)?
	////		('width' width=EFloat)?
	////		('height' height=EFloat)?
	////		('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	////		('insets' insets=KInsets)?
	////    '}';
	//	{KShapeLayout} "KShapeLayout" "{" ("xpos" xpos=EFloat)? ("ypos" ypos=EFloat)? ("width" width=EFloat)? ("height"
	//	height=EFloat)? ("insets" insets=KInsets)? ("mapProperties" ":" persistentEntries+=PersistentEntry (","
	//	persistentEntries+=PersistentEntry)*)? "}";
	public KLayoutDataGrammarAccess.KShapeLayoutElements getKShapeLayoutAccess() {
		return gaKRendering.getKShapeLayoutAccess();
	}
	
	public ParserRule getKShapeLayoutRule() {
		return getKShapeLayoutAccess().getRule();
	}

	//KInsets:
	//	{KInsets} "KInsets" "{" ("top" top=EFloat)? ("bottom" bottom=EFloat)? ("left" left=EFloat)? ("right" right=EFloat)?
	//	"}";
	public KLayoutDataGrammarAccess.KInsetsElements getKInsetsAccess() {
		return gaKRendering.getKInsetsAccess();
	}
	
	public ParserRule getKInsetsRule() {
		return getKInsetsAccess().getRule();
	}

	//KEdgeLayout: //	'KEdgeLayout'
	////	'{'
	////		('persistentEntries' '{' persistentEntries+=PersistentEntry ( "," persistentEntries+=PersistentEntry)* '}' )?
	////		('bendPoints' '{' bendPoints+=KPoint ( "," bendPoints+=KPoint)* '}' )?
	////		'sourcePoint' sourcePoint=KPoint
	////		'targetPoint' targetPoint=KPoint
	////    '}';
	//	"KEdgeLayout" "{" "sourcePoint" sourcePoint=KPoint "targetPoint" targetPoint=KPoint ("bendPoints" ":"
	//	bendPoints+=KPoint ("," bendPoints+=KPoint)*)? ("mapProperties" ":" persistentEntries+=PersistentEntry (","
	//	persistentEntries+=PersistentEntry)*)? "}";
	public KLayoutDataGrammarAccess.KEdgeLayoutElements getKEdgeLayoutAccess() {
		return gaKRendering.getKEdgeLayoutAccess();
	}
	
	public ParserRule getKEdgeLayoutRule() {
		return getKEdgeLayoutAccess().getRule();
	}

	//KPoint: //	{KPoint}
	////	'KPoint'
	////	'{'
	////		('x' x=EFloat)?
	////		('y' y=EFloat)?
	////    '}';
	//	{KPoint} "KPoint" ("x" x=EFloat) ("y" y=EFloat);
	public KLayoutDataGrammarAccess.KPointElements getKPointAccess() {
		return gaKRendering.getKPointAccess();
	}
	
	public ParserRule getKPointRule() {
		return getKPointAccess().getRule();
	}

	//PersistentEntry returns kgraph::PersistentEntry: //	'PersistentEntry'
	////	'{'
	////		'key' key=EString
	////		('value' value=EString)?
	////    '}';
	//	key=EString ("=" value=EString)?;
	public KLayoutDataGrammarAccess.PersistentEntryElements getPersistentEntryAccess() {
		return gaKRendering.getPersistentEntryAccess();
	}
	
	public ParserRule getPersistentEntryRule() {
		return getPersistentEntryAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public KLayoutDataGrammarAccess.EStringElements getEStringAccess() {
		return gaKRendering.getEStringAccess();
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaKRendering.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaKRendering.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaKRendering.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaKRendering.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaKRendering.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaKRendering.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaKRendering.getANY_OTHERRule();
	} 
}
