/*
 * KIELER - Kiel Integrated Environment for Layout Eclipse RichClient
 * 
 * http://www.informatik.uni-kiel.de/rtsys/kieler/
 * 
 * Copyright 2012 by
 * + Christian-Albrechts-University of Kiel
 *   + Department of Computer Science
 *     + Real-Time and Embedded Systems Group
 * 
 * This code is provided under the terms of the Eclipse Public License (EPL).
 * See the file epl-v10.html for the license text.
 */
package de.cau.cs.kieler.core.kgraph.text.krendering.ui.contentassist;

/**
 * See http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to
 * customize content assistant.
 * 
 * @author generated by Xtext
 * @kieler.ignore (excluded from review process)
 */
public class KRenderingProposalProvider extends AbstractKRenderingProposalProvider {

}
