/*
 * generated by Xtext
 */
package de.cau.cs.kieler.kiml.klayoutdata.text.scoping;

import de.cau.cs.kieler.core.kgraph.text.scoping.KGraphScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class KLayoutDataScopeProvider extends KGraphScopeProvider {

}
