/*
 * generated by Xtext 2.9.2
 */
package de.cau.cs.kieler.kgraph.text.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class GRandomScopeProvider extends AbstractGRandomScopeProvider {

}
