/**
 * generated by Xtext 2.9.2
 */
package de.cau.cs.kieler.kgraph.text.grandom;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Configuration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.cau.cs.kieler.kgraph.text.grandom.Configuration#getSamples <em>Samples</em>}</li>
 *   <li>{@link de.cau.cs.kieler.kgraph.text.grandom.Configuration#getForm <em>Form</em>}</li>
 *   <li>{@link de.cau.cs.kieler.kgraph.text.grandom.Configuration#getNodes <em>Nodes</em>}</li>
 *   <li>{@link de.cau.cs.kieler.kgraph.text.grandom.Configuration#getEdges <em>Edges</em>}</li>
 *   <li>{@link de.cau.cs.kieler.kgraph.text.grandom.Configuration#isMW <em>MW</em>}</li>
 *   <li>{@link de.cau.cs.kieler.kgraph.text.grandom.Configuration#getMaxWidth <em>Max Width</em>}</li>
 *   <li>{@link de.cau.cs.kieler.kgraph.text.grandom.Configuration#isMD <em>MD</em>}</li>
 *   <li>{@link de.cau.cs.kieler.kgraph.text.grandom.Configuration#getMaxDegree <em>Max Degree</em>}</li>
 *   <li>{@link de.cau.cs.kieler.kgraph.text.grandom.Configuration#isPF <em>PF</em>}</li>
 *   <li>{@link de.cau.cs.kieler.kgraph.text.grandom.Configuration#getFraction <em>Fraction</em>}</li>
 *   <li>{@link de.cau.cs.kieler.kgraph.text.grandom.Configuration#getHierarchy <em>Hierarchy</em>}</li>
 *   <li>{@link de.cau.cs.kieler.kgraph.text.grandom.Configuration#getSeed <em>Seed</em>}</li>
 *   <li>{@link de.cau.cs.kieler.kgraph.text.grandom.Configuration#getFormat <em>Format</em>}</li>
 *   <li>{@link de.cau.cs.kieler.kgraph.text.grandom.Configuration#getFilename <em>Filename</em>}</li>
 * </ul>
 *
 * @see de.cau.cs.kieler.kgraph.text.grandom.GrandomPackage#getConfiguration()
 * @model
 * @generated
 */
public interface Configuration extends EObject
{
  /**
   * Returns the value of the '<em><b>Samples</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Samples</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Samples</em>' attribute.
   * @see #setSamples(int)
   * @see de.cau.cs.kieler.kgraph.text.grandom.GrandomPackage#getConfiguration_Samples()
   * @model
   * @generated
   */
  int getSamples();

  /**
   * Sets the value of the '{@link de.cau.cs.kieler.kgraph.text.grandom.Configuration#getSamples <em>Samples</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Samples</em>' attribute.
   * @see #getSamples()
   * @generated
   */
  void setSamples(int value);

  /**
   * Returns the value of the '<em><b>Form</b></em>' attribute.
   * The literals are from the enumeration {@link de.cau.cs.kieler.kgraph.text.grandom.Form}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Form</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Form</em>' attribute.
   * @see de.cau.cs.kieler.kgraph.text.grandom.Form
   * @see #setForm(Form)
   * @see de.cau.cs.kieler.kgraph.text.grandom.GrandomPackage#getConfiguration_Form()
   * @model
   * @generated
   */
  Form getForm();

  /**
   * Sets the value of the '{@link de.cau.cs.kieler.kgraph.text.grandom.Configuration#getForm <em>Form</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Form</em>' attribute.
   * @see de.cau.cs.kieler.kgraph.text.grandom.Form
   * @see #getForm()
   * @generated
   */
  void setForm(Form value);

  /**
   * Returns the value of the '<em><b>Nodes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nodes</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nodes</em>' containment reference.
   * @see #setNodes(Nodes)
   * @see de.cau.cs.kieler.kgraph.text.grandom.GrandomPackage#getConfiguration_Nodes()
   * @model containment="true"
   * @generated
   */
  Nodes getNodes();

  /**
   * Sets the value of the '{@link de.cau.cs.kieler.kgraph.text.grandom.Configuration#getNodes <em>Nodes</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nodes</em>' containment reference.
   * @see #getNodes()
   * @generated
   */
  void setNodes(Nodes value);

  /**
   * Returns the value of the '<em><b>Edges</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Edges</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Edges</em>' containment reference.
   * @see #setEdges(Edges)
   * @see de.cau.cs.kieler.kgraph.text.grandom.GrandomPackage#getConfiguration_Edges()
   * @model containment="true"
   * @generated
   */
  Edges getEdges();

  /**
   * Sets the value of the '{@link de.cau.cs.kieler.kgraph.text.grandom.Configuration#getEdges <em>Edges</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Edges</em>' containment reference.
   * @see #getEdges()
   * @generated
   */
  void setEdges(Edges value);

  /**
   * Returns the value of the '<em><b>MW</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>MW</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>MW</em>' attribute.
   * @see #setMW(boolean)
   * @see de.cau.cs.kieler.kgraph.text.grandom.GrandomPackage#getConfiguration_MW()
   * @model
   * @generated
   */
  boolean isMW();

  /**
   * Sets the value of the '{@link de.cau.cs.kieler.kgraph.text.grandom.Configuration#isMW <em>MW</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>MW</em>' attribute.
   * @see #isMW()
   * @generated
   */
  void setMW(boolean value);

  /**
   * Returns the value of the '<em><b>Max Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Max Width</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max Width</em>' attribute.
   * @see #setMaxWidth(Integer)
   * @see de.cau.cs.kieler.kgraph.text.grandom.GrandomPackage#getConfiguration_MaxWidth()
   * @model
   * @generated
   */
  Integer getMaxWidth();

  /**
   * Sets the value of the '{@link de.cau.cs.kieler.kgraph.text.grandom.Configuration#getMaxWidth <em>Max Width</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max Width</em>' attribute.
   * @see #getMaxWidth()
   * @generated
   */
  void setMaxWidth(Integer value);

  /**
   * Returns the value of the '<em><b>MD</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>MD</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>MD</em>' attribute.
   * @see #setMD(boolean)
   * @see de.cau.cs.kieler.kgraph.text.grandom.GrandomPackage#getConfiguration_MD()
   * @model
   * @generated
   */
  boolean isMD();

  /**
   * Sets the value of the '{@link de.cau.cs.kieler.kgraph.text.grandom.Configuration#isMD <em>MD</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>MD</em>' attribute.
   * @see #isMD()
   * @generated
   */
  void setMD(boolean value);

  /**
   * Returns the value of the '<em><b>Max Degree</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Max Degree</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max Degree</em>' attribute.
   * @see #setMaxDegree(Integer)
   * @see de.cau.cs.kieler.kgraph.text.grandom.GrandomPackage#getConfiguration_MaxDegree()
   * @model
   * @generated
   */
  Integer getMaxDegree();

  /**
   * Sets the value of the '{@link de.cau.cs.kieler.kgraph.text.grandom.Configuration#getMaxDegree <em>Max Degree</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max Degree</em>' attribute.
   * @see #getMaxDegree()
   * @generated
   */
  void setMaxDegree(Integer value);

  /**
   * Returns the value of the '<em><b>PF</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>PF</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>PF</em>' attribute.
   * @see #setPF(boolean)
   * @see de.cau.cs.kieler.kgraph.text.grandom.GrandomPackage#getConfiguration_PF()
   * @model
   * @generated
   */
  boolean isPF();

  /**
   * Sets the value of the '{@link de.cau.cs.kieler.kgraph.text.grandom.Configuration#isPF <em>PF</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>PF</em>' attribute.
   * @see #isPF()
   * @generated
   */
  void setPF(boolean value);

  /**
   * Returns the value of the '<em><b>Fraction</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fraction</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fraction</em>' containment reference.
   * @see #setFraction(DoubleQuantity)
   * @see de.cau.cs.kieler.kgraph.text.grandom.GrandomPackage#getConfiguration_Fraction()
   * @model containment="true"
   * @generated
   */
  DoubleQuantity getFraction();

  /**
   * Sets the value of the '{@link de.cau.cs.kieler.kgraph.text.grandom.Configuration#getFraction <em>Fraction</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fraction</em>' containment reference.
   * @see #getFraction()
   * @generated
   */
  void setFraction(DoubleQuantity value);

  /**
   * Returns the value of the '<em><b>Hierarchy</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Hierarchy</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hierarchy</em>' containment reference.
   * @see #setHierarchy(Hierarchy)
   * @see de.cau.cs.kieler.kgraph.text.grandom.GrandomPackage#getConfiguration_Hierarchy()
   * @model containment="true"
   * @generated
   */
  Hierarchy getHierarchy();

  /**
   * Sets the value of the '{@link de.cau.cs.kieler.kgraph.text.grandom.Configuration#getHierarchy <em>Hierarchy</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Hierarchy</em>' containment reference.
   * @see #getHierarchy()
   * @generated
   */
  void setHierarchy(Hierarchy value);

  /**
   * Returns the value of the '<em><b>Seed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Seed</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Seed</em>' attribute.
   * @see #setSeed(Integer)
   * @see de.cau.cs.kieler.kgraph.text.grandom.GrandomPackage#getConfiguration_Seed()
   * @model
   * @generated
   */
  Integer getSeed();

  /**
   * Sets the value of the '{@link de.cau.cs.kieler.kgraph.text.grandom.Configuration#getSeed <em>Seed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Seed</em>' attribute.
   * @see #getSeed()
   * @generated
   */
  void setSeed(Integer value);

  /**
   * Returns the value of the '<em><b>Format</b></em>' attribute.
   * The literals are from the enumeration {@link de.cau.cs.kieler.kgraph.text.grandom.Formats}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Format</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Format</em>' attribute.
   * @see de.cau.cs.kieler.kgraph.text.grandom.Formats
   * @see #setFormat(Formats)
   * @see de.cau.cs.kieler.kgraph.text.grandom.GrandomPackage#getConfiguration_Format()
   * @model
   * @generated
   */
  Formats getFormat();

  /**
   * Sets the value of the '{@link de.cau.cs.kieler.kgraph.text.grandom.Configuration#getFormat <em>Format</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Format</em>' attribute.
   * @see de.cau.cs.kieler.kgraph.text.grandom.Formats
   * @see #getFormat()
   * @generated
   */
  void setFormat(Formats value);

  /**
   * Returns the value of the '<em><b>Filename</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Filename</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filename</em>' attribute.
   * @see #setFilename(String)
   * @see de.cau.cs.kieler.kgraph.text.grandom.GrandomPackage#getConfiguration_Filename()
   * @model
   * @generated
   */
  String getFilename();

  /**
   * Sets the value of the '{@link de.cau.cs.kieler.kgraph.text.grandom.Configuration#getFilename <em>Filename</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Filename</em>' attribute.
   * @see #getFilename()
   * @generated
   */
  void setFilename(String value);

} // Configuration
