/**
 * generated by Xtext 2.10.0
 */
package de.cau.cs.kieler.kgraph.text.grandom;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rand Graph</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.cau.cs.kieler.kgraph.text.grandom.RandGraph#getConfigs <em>Configs</em>}</li>
 * </ul>
 *
 * @see de.cau.cs.kieler.kgraph.text.grandom.GrandomPackage#getRandGraph()
 * @model
 * @generated
 */
public interface RandGraph extends EObject
{
  /**
   * Returns the value of the '<em><b>Configs</b></em>' containment reference list.
   * The list contents are of type {@link de.cau.cs.kieler.kgraph.text.grandom.Configuration}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Configs</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Configs</em>' containment reference list.
   * @see de.cau.cs.kieler.kgraph.text.grandom.GrandomPackage#getRandGraph_Configs()
   * @model containment="true"
   * @generated
   */
  EList<Configuration> getConfigs();

} // RandGraph
