/*
 * KIELER - Kiel Integrated Environment for Layout Eclipse RichClient
 * 
 * http://www.informatik.uni-kiel.de/rtsys/kieler/
 * 
 * Copyright 2012 by
 * + Christian-Albrechts-University of Kiel
 *   + Department of Computer Science
 *     + Real-Time and Embedded Systems Group
 * 
 * This code is provided under the terms of the Eclipse Public License (EPL).
 * See the file epl-v10.html for the license text.
 */
package de.cau.cs.kieler.core.kgraph.text.klayoutdata.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 * 
 * @author generated by Xtext
 * @kieler.ignore (excluded from review process)
 */
public class KLayoutDataUiModule extends AbstractKLayoutDataUiModule {

    /**
     * Standard constructor.
     * 
     * @param plugin
     *            the activator class of the containing bundle.
     */
    public KLayoutDataUiModule(final AbstractUIPlugin plugin) {
        super(plugin);
    }
}
