/*
* generated by Xtext
*/
package de.cau.cs.kieler.core.kgraph.text.krendering.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.cau.cs.kieler.core.kgraph.text.krendering.services.KRenderingGrammarAccess;

public class KRenderingParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private KRenderingGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.cau.cs.kieler.core.kgraph.text.krendering.parser.antlr.internal.InternalKRenderingParser createParser(XtextTokenStream stream) {
		return new de.cau.cs.kieler.core.kgraph.text.krendering.parser.antlr.internal.InternalKRenderingParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "KRenderingLibrary";
	}
	
	public KRenderingGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(KRenderingGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
