/*
* generated by Xtext
*/
package de.cau.cs.kieler.kiml.klayoutdata.text.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import de.cau.cs.kieler.kiml.klayoutdata.text.services.KLayoutDataGrammarAccess;

public class KLayoutDataParser extends AbstractContentAssistParser {
	
	@Inject
	private KLayoutDataGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected de.cau.cs.kieler.kiml.klayoutdata.text.ui.contentassist.antlr.internal.InternalKLayoutDataParser createParser() {
		de.cau.cs.kieler.kiml.klayoutdata.text.ui.contentassist.antlr.internal.InternalKLayoutDataParser result = new de.cau.cs.kieler.kiml.klayoutdata.text.ui.contentassist.antlr.internal.InternalKLayoutDataParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getEFloatAccess().getAlternatives_4_0(), "rule__EFloat__Alternatives_4_0");
					put(grammarAccess.getKShapeLayoutAccess().getGroup(), "rule__KShapeLayout__Group__0");
					put(grammarAccess.getKShapeLayoutAccess().getGroup_3(), "rule__KShapeLayout__Group_3__0");
					put(grammarAccess.getKShapeLayoutAccess().getGroup_4(), "rule__KShapeLayout__Group_4__0");
					put(grammarAccess.getKShapeLayoutAccess().getGroup_5(), "rule__KShapeLayout__Group_5__0");
					put(grammarAccess.getKShapeLayoutAccess().getGroup_6(), "rule__KShapeLayout__Group_6__0");
					put(grammarAccess.getKShapeLayoutAccess().getGroup_7(), "rule__KShapeLayout__Group_7__0");
					put(grammarAccess.getKShapeLayoutAccess().getGroup_8(), "rule__KShapeLayout__Group_8__0");
					put(grammarAccess.getKShapeLayoutAccess().getGroup_8_3(), "rule__KShapeLayout__Group_8_3__0");
					put(grammarAccess.getKInsetsAccess().getGroup(), "rule__KInsets__Group__0");
					put(grammarAccess.getKInsetsAccess().getGroup_3(), "rule__KInsets__Group_3__0");
					put(grammarAccess.getKInsetsAccess().getGroup_4(), "rule__KInsets__Group_4__0");
					put(grammarAccess.getKInsetsAccess().getGroup_5(), "rule__KInsets__Group_5__0");
					put(grammarAccess.getKInsetsAccess().getGroup_6(), "rule__KInsets__Group_6__0");
					put(grammarAccess.getKEdgeLayoutAccess().getGroup(), "rule__KEdgeLayout__Group__0");
					put(grammarAccess.getKEdgeLayoutAccess().getGroup_6(), "rule__KEdgeLayout__Group_6__0");
					put(grammarAccess.getKEdgeLayoutAccess().getGroup_6_3(), "rule__KEdgeLayout__Group_6_3__0");
					put(grammarAccess.getKEdgeLayoutAccess().getGroup_7(), "rule__KEdgeLayout__Group_7__0");
					put(grammarAccess.getKEdgeLayoutAccess().getGroup_7_3(), "rule__KEdgeLayout__Group_7_3__0");
					put(grammarAccess.getKPointAccess().getGroup(), "rule__KPoint__Group__0");
					put(grammarAccess.getKPointAccess().getGroup_2(), "rule__KPoint__Group_2__0");
					put(grammarAccess.getKPointAccess().getGroup_3(), "rule__KPoint__Group_3__0");
					put(grammarAccess.getPersistentEntryAccess().getGroup(), "rule__PersistentEntry__Group__0");
					put(grammarAccess.getPersistentEntryAccess().getGroup_4(), "rule__PersistentEntry__Group_4__0");
					put(grammarAccess.getEFloatAccess().getGroup(), "rule__EFloat__Group__0");
					put(grammarAccess.getEFloatAccess().getGroup_4(), "rule__EFloat__Group_4__0");
					put(grammarAccess.getKShapeLayoutAccess().getXposAssignment_3_1(), "rule__KShapeLayout__XposAssignment_3_1");
					put(grammarAccess.getKShapeLayoutAccess().getYposAssignment_4_1(), "rule__KShapeLayout__YposAssignment_4_1");
					put(grammarAccess.getKShapeLayoutAccess().getWidthAssignment_5_1(), "rule__KShapeLayout__WidthAssignment_5_1");
					put(grammarAccess.getKShapeLayoutAccess().getHeightAssignment_6_1(), "rule__KShapeLayout__HeightAssignment_6_1");
					put(grammarAccess.getKShapeLayoutAccess().getInsetsAssignment_7_1(), "rule__KShapeLayout__InsetsAssignment_7_1");
					put(grammarAccess.getKShapeLayoutAccess().getPersistentEntriesAssignment_8_2(), "rule__KShapeLayout__PersistentEntriesAssignment_8_2");
					put(grammarAccess.getKShapeLayoutAccess().getPersistentEntriesAssignment_8_3_1(), "rule__KShapeLayout__PersistentEntriesAssignment_8_3_1");
					put(grammarAccess.getKInsetsAccess().getTopAssignment_3_1(), "rule__KInsets__TopAssignment_3_1");
					put(grammarAccess.getKInsetsAccess().getBottomAssignment_4_1(), "rule__KInsets__BottomAssignment_4_1");
					put(grammarAccess.getKInsetsAccess().getLeftAssignment_5_1(), "rule__KInsets__LeftAssignment_5_1");
					put(grammarAccess.getKInsetsAccess().getRightAssignment_6_1(), "rule__KInsets__RightAssignment_6_1");
					put(grammarAccess.getKEdgeLayoutAccess().getSourcePointAssignment_3(), "rule__KEdgeLayout__SourcePointAssignment_3");
					put(grammarAccess.getKEdgeLayoutAccess().getTargetPointAssignment_5(), "rule__KEdgeLayout__TargetPointAssignment_5");
					put(grammarAccess.getKEdgeLayoutAccess().getBendPointsAssignment_6_2(), "rule__KEdgeLayout__BendPointsAssignment_6_2");
					put(grammarAccess.getKEdgeLayoutAccess().getBendPointsAssignment_6_3_1(), "rule__KEdgeLayout__BendPointsAssignment_6_3_1");
					put(grammarAccess.getKEdgeLayoutAccess().getPersistentEntriesAssignment_7_2(), "rule__KEdgeLayout__PersistentEntriesAssignment_7_2");
					put(grammarAccess.getKEdgeLayoutAccess().getPersistentEntriesAssignment_7_3_1(), "rule__KEdgeLayout__PersistentEntriesAssignment_7_3_1");
					put(grammarAccess.getKPointAccess().getXAssignment_2_1(), "rule__KPoint__XAssignment_2_1");
					put(grammarAccess.getKPointAccess().getYAssignment_3_1(), "rule__KPoint__YAssignment_3_1");
					put(grammarAccess.getPersistentEntryAccess().getKeyAssignment_3(), "rule__PersistentEntry__KeyAssignment_3");
					put(grammarAccess.getPersistentEntryAccess().getValueAssignment_4_1(), "rule__PersistentEntry__ValueAssignment_4_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			de.cau.cs.kieler.kiml.klayoutdata.text.ui.contentassist.antlr.internal.InternalKLayoutDataParser typedParser = (de.cau.cs.kieler.kiml.klayoutdata.text.ui.contentassist.antlr.internal.InternalKLayoutDataParser) parser;
			typedParser.entryRuleKShapeLayout();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public KLayoutDataGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(KLayoutDataGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
