/*
 * KIELER - Kiel Integrated Environment for Layout Eclipse RichClient
 * 
 * http://www.informatik.uni-kiel.de/rtsys/kieler/
 * 
 * Copyright 2012 by
 * + Christian-Albrechts-University of Kiel
 *   + Department of Computer Science
 *     + Real-Time and Embedded Systems Group
 * 
 * This code is provided under the terms of the Eclipse Public License (EPL).
 * See the file epl-v10.html for the license text.
 */
package de.cau.cs.kieler.core.kgraph.text.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 * 
 * @author generated by Xtext
 * @kieler.ignore (excluded from review process)
 */
public class KGraphUiModule extends AbstractKGraphUiModule {

    /**
     * Standard constructor.
     * 
     * @param plugin
     *            the activator class of the containing bundle.
     */
    public KGraphUiModule(final AbstractUIPlugin plugin) {
        super(plugin);
    }
    
    /**
     * Registers custom {@link org.eclipse.xtext.ui.editor.model.edit.ITextEditComposer
     * ITextEditComposer}.
     * 
     * @return the text edit composer class
     */
    public Class<? extends org.eclipse.xtext.ui.editor.model.edit.ITextEditComposer> bindITextEditComposer() {
        return KGraphTextEditComposer.class; // SUPPRESS CHECKSTYLE PREVIOUS LineLength
    }

}
