/*
 * generated by Xtext
 */
package de.cau.cs.kieler.core.kgraph.text.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class KGraphUiModule extends de.cau.cs.kieler.core.kgraph.text.ui.AbstractKGraphUiModule {
	public KGraphUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
