/*
 * generated by Xtext 2.9.2
 */
package de.cau.cs.kieler.kgraph.text.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGRandomScopeProvider extends DelegatingScopeProvider {
}
