/*
 * generated by Xtext
 */
package de.cau.cs.kieler.core.kgraph.text.klayoutdata;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class KLayoutDataRuntimeModule extends AbstractKLayoutDataRuntimeModule {

}
